### PR TITLE
install webui env

### PR DESCRIPTION
**Pull request by ljleb**
install the webui torch version, so that the pipeline does not break randomly after 1 month.

### CODE REVIEW

**Comment by ljleb** [comment]
well I guess I should have seen this coming. tl;dr: torch is unable to be installed from launch.py for some reason.

**Comment by lllyasviel** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/5ab7f213bec2f816f9c5644becb32eb72c8ffb89/launch.py#L225

**Comment by ljleb** [comment]
Yes I know, this is why I opened this PR.

**Comment by ljleb** [comment]
I am confused. Is this because the workflow cached the torch and torchvision version?

diff: https://github.com/Mikubill/sd-webui-controlnet/compare/main...ljleb:sd-webui-controlnet:use-webui-versions#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fL33

job: https://github.com/ljleb/sd-webui-controlnet/actions/runs/4898720046/jobs/8748104753

**Comment by ljleb** [comment]
strangely enough, the tests pass on push actions but fails on pull_request actions.

**Comment by ljleb** [comment]
You can see here that it works when the action is triggered from a push event: https://github.com/ljleb/sd-webui-controlnet/commits/use-webui-versions

**Comment by ljleb** [comment]
The corresponding push workflow: https://github.com/ljleb/sd-webui-controlnet/actions/runs/4898927834/jobs/8748494587

**Comment by ljleb** [comment]
Alright I spent too much time on this. Reopen when the pipeline fails because of unexpected torch and tv versions.

**Pull request closed without merging**
