### PR TITLE
[Unittest] Add txt2img test with every preprocessors

### PR DESCRIPTION
**Pull request by huchenlei**
This PR addresses #1101.

### CODE REVIEW

**Comment by huchenlei** [comment]
Runner says:
```
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
```

But I did not cancel it manually.

**Comment by lllyasviel** [comment]
maybe many preprocessor need gpu

**Comment by lllyasviel** [comment]
wait it seems that new a1111 break all github tests

**Comment by huchenlei** [comment]
Seems like we don't have necessary resources to run every preprocessor in github CI. I will make the test running locally presubmit.

**Comment by lllyasviel** [comment]
what  about only test openpose_full and depth

**Comment by lllyasviel** [comment]
wow the test passed, merge here?

**Comment by huchenlei** [comment]
Sure we can add more coverage if we fell necessary later.

**Pull request merged**
