### PR TITLE
Add some items to X/Y/Z plot (2)

### PR DESCRIPTION
**Pull request by aiton-sd**
### add X/Y/Z plot items
- Model
- Guidance Strength
- Preprocessor

### fix typo
- stength to strength

### CODE REVIEW

**Comment by Ev-Bro** [comment]
Is it possible to automatically use the matching model for each preprocessor? Or use a model/preprocessor pair on a single axis. Thank you.

**Comment by PaperOrb** [comment]
Agreed, controlnet needs way more options for automation, and model+preprocessor combo per axis would be a decent start.

**Comment by Ev-Bro** [comment]
Weird coincidence, but they actually added controlnet presets yesterday, to the auto1111 ext.

**Comment by PaperOrb** [comment]
@Ev-Bro not seeing the commit or how to use it

**Comment by Ev-Bro** [comment]
This thing within ControlNet
image

**Comment by Jilocasin** [comment]
I think the discussion was about the ability to control the selection of preprocessor and model from within the XYZ plot dropdown, like here. While there are some options available, I don't see a way to pick one of these new "Control Types". Am I missing something?

grafik

**Comment by shihanqu** [comment]
This needs attention! It's useless to have "[ControlNet] Model" be an option, unless we are able to define the entire preprocessor/model pair.

**Comment by Jilocasin** [comment]
Since this was merged and probably closed, it may not receive any attention from the devs this way.
Would it be the better option to open another issue for that?

**Comment by PaperOrb** [comment]
@Jilocasin It's looking like that might be a good idea.

**Comment by shihanqu** [comment]
@Mikubill are you able to re-open this request? Or does a new issue need to be opened?

**Pull request merged**
