### PR TITLE
refactor: multi-controlnet support

### PR DESCRIPTION
**Pull request by Mikubill**
~~Note that this may break current API and script control.~~ Fixed

### CODE REVIEW

**Comment by Mikubill** [comment]
Quick test, also slightly improved memory usage.

| Source A | Source B | Output |
|:-------------------------:|:-------------------------:|:-------------------------:|
|  |   |  |

**Comment by GeekyGhost** [comment]
This is looking good. Great work!

**Comment by ClashSAN** [comment]
you will eventually get a user request for the slider to allow more than 5 controlnets, due to their re-usage of the same ones. 10 seems good enough.

**Comment by henbucuoshanghai** [comment]
multi-controlnet。 where is the code?tks

**Pull request merged**
