### PR TITLE
add lowvram option

### PR DESCRIPTION
**Pull request by hnmr293**
Thank you for your great extension. I have been using it 👍. 

This PR adds `low vram` option for users with low VRAM.
My code is based on the original ControlNet's low_vram option ([commit: 1e5c75a](https://github.com/lllyasviel/ControlNet/commit/1e5c75a5cfb45c3fc727a152238045fb51f5660a)).

Best regards,

### CODE REVIEW

**Comment by hnmr293** [comment]
a

**Comment by Mikubill** [comment]
Looks good! Will this compatible with WebUI's lowvram mode?

**Comment by hnmr293** [comment]
Yes, this dose actually same thing with WebUI's `--lowvram` mode - move Text Encoder and VAE from GPU to CPU when they are not needed.
And I (and some guys) have confirmed that this works also fine with WebUI's `--lowvram` option.
Thank you.

**Comment by Mikubill** [comment]
Great! Thanks for your contribution

**Pull request merged**
