### PR TITLE
proper is_img2img implementation

### LINKED ISSUE #182: If "Skip img2img processing when using img2img initial image" is enabled and Batch img2img is executed, an error occurs.
If "Skip img2img processing when using img2img initial image" is enabled and Batch img2img is executed, an error occurs.

If I disable that option there is no problem.

image

```
Error completing request:20,  5.63it/s]
Arguments: ('task(7yr4b1mfufzb3sd)', 5, 'masterpiece, best quality, 1girl, solo, stair, indoor, window, concrete, trash can, trash, can, gas tank, blue sky, white cloud, sniper rifle, cable, looking at viewer,', '(worst quality, low quality:1.4), watermark, artist name,', [], None, None, None, None, None, None, None, 20, 15, 4, 0, 0, False, False, 1, 1, 7, 1.5, 0.75, 1972617717.0, -1.0, 0, 0, 0, False, 768, 512, 0, 0, 32, 0, 'D:\\Desktop\\testmocap_01\\dsdsd', 'D:\\Desktop\\testmocap_01\\dsdsd\\dd', '', [], 0, 0, 0, 0, 0, 0.25, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'Refresh models', True, 'none', 'control_sd15_openpose [fef5e48e]', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, [], False, True, 'Denoised', 1.0, 0.0, 0.0, True, 'gif', 'h264', 2.0, 0.0, 0.0, False, 0.0, True, True, False, '', False, False, False, False, 'Auto', 0.5, 1, False, False, 1, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 1, 0, '#000000', True, False, 0, 256, 0, None, '', 0.2, 0.1, 1, 1, False, True, True, False, False, False, False, 4, 1, 4, 0.09, True, 1, 0, 7, False, False, 'Show/Hide AlphaCanvas', 384, 'Update Outpainting Size', 8, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 'Positive', 0, ', ', True, 32, 1, '', 0, '', 0, '', True, False, False, False, 0, False, None, True, None, None, False, True, True, True, 0, 0, 384, 384, False, False, True, True, True, False, True, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False, 0, 1, 384, 384, True, False, True, True, True, False, 1, True, 3, False, 3, False, 3, 1, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 2, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\img2img.py", line 163, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "C:\stable-diffusion-webui\modules\img2img.py", line 76, in process_batch
    processed_image.save(os.path.join(output_dir, filename))
AttributeError: 'numpy.ndarray' object has no attribute 'save'
```

### PR DESCRIPTION
**Pull request by ljleb**
closes #182.

I hope this is the last fix PR I have to open for the batch detection code 😅

Feel free to edit the code if you see a simpler way to test whether we are in an img2img tab.

### CODE REVIEW

**Comment by ljleb** [comment]
I changed all the selectors `.` to `getattr` in `Img2ImgTabTracker::on_after_component_callback`. We should not get any more `object has no attribute` errors in this region of the code at least (see #181). I'm guessing this was caused by a different gradio version?

**Comment by Mikubill** [comment]
Since it may break APIs, will merge after API stuff finished.

**Comment by joseph-schwartz** [comment]
is_img2img batch error
Getting this error when making api calls to control net.  Specifically here it's the depth model.  Works fine from the Automatic1111 GUI, but when I make calls from the API, it takes one call with a batch_size of 1 and somehow errors out and keeps repeating the generation multiple times until it stops with errors along the way like this.  Any ideas?

**Comment by ljleb** [comment]
Ah the api does not call the `ui()` function it passes its own args. I'll open another PR.

**Comment by joseph-schwartz** [comment]
This has since cleared up, I believe someone fixed it :)

**Pull request merged**
