### PR TITLE
Fix linter issues under `/script`

### PR DESCRIPTION
**Pull request by huchenlei**
Fix many linter errors in under `/script`.

### CODE REVIEW

**Comment by Myoko** [comment]
When i using inpaint with adetailer, I got an error message "diffusionwrapper.forward() missing 2 required positional arguments: 'x' and 't'".

**Comment by huchenlei** [comment]
> When i using inpaint model in adetailer, I got an error message "diffusionwrapper.forward() missing 2 required positional arguments: 'x' and 't'".

Please file a separate issue. I do not think this PR causes the issue as no function signature has changed.

**Comment by Myoko** [comment]
> > When i using inpaint model in adetailer, I got an error message "diffusionwrapper.forward() missing 2 required positional arguments: 'x' and 't'".
> 
> Please file a separate issue. I do not think this PR causes the issue as no function signature has changed.

I'm not sure if this PR is the cause of the problem, i trying to roll back PR#2666 and everything is normal.

**Comment by huchenlei** [comment]
I think you can ignore this error for now. I think the error was previously discarded silently here:
```python
                try:
                    # Trigger the register_forward_pre_hook
                    outer.sd_ldm.model()
                except Exception as e:
                    logger.error(e)
```

Now after the change we just report it.

I will change the log level for that log to `debug` so you won't see it normally.

**Comment by Myoko** [comment]
> You can ignore this error for now, the functionality is unchanged. I think the error was previously discarded silently here:
> 
> ```python
>                 try:
>                     # Trigger the register_forward_pre_hook
>                     outer.sd_ldm.model()
>                 except Exception as e:
>                     logger.error(e)
> ```
> 
> Now after the change we just report it.
> 
> I will change the log level for that log to `debug` so you won't see it normally.

I thought this error loading inpaint model failed! OK, thank you.

**Pull request merged**
