### PR TITLE
Revert "Add typecheck on script args"

### PR DESCRIPTION
**Pull request by lllyasviel**
Reverts Mikubill/sd-webui-controlnet#1678

close https://github.com/lllyasviel/ControlNet/issues/447 https://github.com/Mikubill/sd-webui-controlnet/discussions/1682 https://github.com/Mikubill/sd-webui-controlnet/commit/784eadbba6600b3ecc2e3b07363895e42d6b3e8f#commitcomment-119412946 https://github.com/Mikubill/sd-webui-controlnet/commit/784eadbba6600b3ecc2e3b07363895e42d6b3e8f#commitcomment-119423589

### CODE REVIEW

**Comment by NiuDaVinci** [comment]
I don't understand, how do i fix the WARNING?

**Comment by huchenlei** [comment]
I am really confused on why you are getting this warning, as `UiControlNetUnit` extends `ControlNetUnit` and should pass that type check. 

I have no problem running the code locally.

**Comment by lllyasviel** [comment]
and anything beyond the reloading shoud push version ahead - this will need 225 so that we know if user restarted terminal

**Comment by lllyasviel** [comment]
and here is another problem https://github.com/Mikubill/sd-webui-controlnet/discussions/1684

**Pull request merged**
