### PR TITLE
Add support for ControlNet 1.1

### PR DESCRIPTION
**Pull request by Mikubill**

### CODE REVIEW

**Comment by CCRcmcpe** [comment]
Currently `sketch_anime` annotator has conflicts with the built-in LoRA extension of A41 webui because it hooks `torch.Linear` and `torch.Conv2d.forward`. I plan to solve this later.

**Comment by hithereai** [comment]
```
File "D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 543, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'str' object has no attribute 'enabled'
```

**Comment by dermesut** [comment]
> ```
> File "D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 543, in parse_remote_call
>     unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
> AttributeError: 'str' object has no attribute 'enabled'
> ```

so, i don't know why i found this error message in this thread, but at least i found it somewhere.
i updated sd and controlnet after... not sure... maybe about a week or ten days or so of not using any of those.
and now i can't use controlnet via api anymore. it gives me the above message; the complete version of it would be:

"Error running process: E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\ai\_gh_repos\sd.webui\webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 631, in process
    unit = self.parse_remote_call(p, unit, idx)
  File "E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 543, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'str' object has no attribute 'enabled'"

i don't seem to be able to find changes in the last 10 days, that may have triggered this.

usage of controlnet via sd-webui web-interface works, though.

**Comment by ljleb** [comment]
> > File "D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 543, in parse_remote_call
> >     unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
> > AttributeError: 'str' object has no attribute 'enabled'
> 
> i don't seem to be able to find changes in the last 10 days, that may have triggered this.

I don't think this is related to this PR. The API requires users to pass exactly the max amount of controlnet units because of an implementation quirk at the moment. I am not sure why you did not get this error before. See https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9130 for a fix.

**Comment by dermesut** [comment]
> > > File "D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 543, in parse_remote_call
> > > unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
> > > AttributeError: 'str' object has no attribute 'enabled'
> > 
> > 
> > i don't seem to be able to find changes in the last 10 days, that may have triggered this.
> 
> I don't think this is related to this PR. The API requires users to pass exactly the max amount of controlnet units because of an implementation quirk at the moment. I am not sure why you did not get this error before. See [AUTOMATIC1111/stable-diffusion-webui#9130](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9130) for a fix.

this indeed fixed the problem.
thank you.

**Comment by Kanareika** [comment]
Now, the "Shuffle" preprocessor shuffles the image differently, even if the same seed is used. Wouldn't it be better to make it dependent on seed to ensure repeatability of the result?

**Comment by Mikubill** [comment]
Almost done, currently it should support all controlnet 1.1 models (except inpaint and tile).

New Annotators:
* openpose/openpose_hand/openpose_face
* zoe_depth/normal_bae
* oneformer_coco/oneformer_ade20k
* lineart/lineart_anime/shuffle

Note that `shuffle` requires `Enable CFG-Based guidance` to be enabled (in settings) for better result.
docs wip, (tests and examples welcome).

ControlNet 1.1 checkpoints: https://huggingface.co/lllyasviel/ControlNet-v1-1

**Comment by Mikubill** [comment]
Yes, will merge in future PR with other minor fixes (like lora hook etc, if we could find a way to handle it.

**Comment by lllyasviel** [comment]
> 

I have a smart idea. we use torch to generate a random number and use that number as seed to set numpy. In this way we do not know what seed is in webui. Because for a fixed seed in webui, the random number by torch  should be same

**Comment by lllyasviel** [comment]
oh i just find out that we can get seed from p.seed. cool

**Comment by OedoSoldier** [comment]
CFG-Based guidance option is removed?

**Comment by Mikubill** [comment]
Will add option for cfg-mode back in later PR.

**Comment by lllyasviel** [comment]
I cannot think about any cases where we need cfg-mode. if we really need this, we should have something like official instruct pix2pix's double cfg tuning using two cfg for prompts and images.

**Comment by MariaIvanoff** [comment]
Hi Author. T2I style have stopped working. In version 1.0 everything was fine. Now I am getting message AttributeError: module 'torch' has no attribute 'concatenate' I love this module and would like to continue working in it.

**Comment by creeduk** [comment]
I am getting this error as well but seems only if I select "ControlNet is more important" then I get that message with T2I models. Tried color

**Pull request merged**
