### PR TITLE
Use UNet precision, add `--upcast-sampling` support

### LINKED ISSUE #68: MPS keeps crashing
I got the ControlNet extension loading fine, but it keeps on crashing when I use scribble:

```
  0%|                                                    | 0/20 [00:00<?, ?it/s](mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:228:0: error: 'mps.add' op requires the same element type for all operands and results
(mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:228:0: note: see current operation: %5 = "mps.add"(%4, %arg2) : (tensor<2x1280xf32>, tensor<*xf16>) -> tensor<*xf32>
zsh: segmentation fault  ./webui.sh
/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### LINKED ISSUE #87: MacOS?
Is ControlNet compatible with MacOS.
I could install it, and see it in the webUI, but when I use it, I get following error:

Loading preprocessor: canny, model: control_sd15_canny [fef5e48e]
Loaded state_dict from [/Users/koen/Documents/SD/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_sd15_canny.pth]
ControlNet model control_sd15_canny [fef5e48e] loaded.
0%| | 0/16 [00:00<?, ?it/s]loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":219:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<*xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort ./webui.sh
koen@Koens-MacBook-Pro-2 stable-diffusion-webui % /opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d '

Shortly after "Python quit unexpectedly"

Koen

### PR DESCRIPTION
**Pull request by brkirch**
This will fix Macs needing `--no-half` (by adding dtype casting for `--upcast-sampling`) but also has a significant change - currently the ControlNet models appear to be loaded with full precision by default, this PR changes the precision to match the UNet precision of the loaded model in web UI. Unless there is something I'm missing, this change should significantly reduce VRAM usage for _all_ users that aren't using `--no-half`.

Fixes #87, fixes #68.

### CODE REVIEW

**Comment by Mikubill** [comment]
Looks good. Will do some test later

**Comment by Mikubill** [comment]
Confirm works on M1 Pro and M1. But the result is weird: Looks like something was upscaled inproperly

**Comment by jwooldridge234** [comment]
Just tested on MacOs M1 Pro, can't see any issues and it runs super smooth now. Thanks for the hard work on this!

**Comment by Mikubill** [comment]
Hmm.. any screenshots? Maybe I misconfigured something on my MacBook.

**Comment by jwooldridge234** [comment]
Sure!

I'm only using Scribble at the moment and I always use the preprocessor bc I've found it steers the final image better.
image
image

Here's without the preprocessor:

image

**Comment by jwooldridge234** [comment]
Haven't tested the other models yet, maybe there's issues with those.

**Comment by Mikubill** [comment]
Looks nice. Note that MPS support is experimental, feel free to open issue if you have any questions.

**Comment by brkirch** [comment]
> Confirm works on M1 Pro and M1. But the result is weird: Looks like something was upscaled inproperly

I’m going to guess that it has something to do with the PyTorch version; I’m using nightly builds (from February 10 currently; see https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/7453 for the webui-user.sh file with the exact configuration). In the near future I plan to have PyTorch 2.0 set as the default version for Macs running web UI anyway, so any PRs I submit here will be intended to be used with that webui-user.sh configuration.

**Comment by baigalibao** [comment]
Error
Expecting value: line 1 column 1 (char 0)

recall this problem ,i dont know why

**Pull request merged**
