### PR TITLE
:sparkles: Add hr_option (Both, High res only, Low res only)

### LINKED ISSUE #2378: [Feature Request] More hires fix options
Original discussion: #1826.

We should provide option per ControlNet unit to let user pick how the ControlNet unit should apply:
- To both pass
- Only low res pass
- Only high res pass

### PR DESCRIPTION
**Pull request by huchenlei**
Closes #2378.

This PR removes global option `control_net_no_high_res_fix`, and adds the radio selection for hr option per ControlNet unit.

### CODE REVIEW

**Comment by huchenlei** [comment]
Previously disabling highres pass was available so I guess there is sufficient usecases being explored. Here just some novel uses enabled by this PR.

Now you can use tile model to control highres pass.

ControlNet input image:
download (2)

Step1: non-highres generation, with canny edge unit:


Step2: Reuse seed. Highres generation with 2 units:
- canny edge (set to lowres pass only)
- tile (input is the generation result from step1) (set to highres pass only)
00009-1924817058_hires

I am not sure whether this method is superior than the img2img upscale method (tile + SD Ultimate upscale script), but at least there is another option now 😄.

**Comment by huchenlei** [comment]
Tile + SD Ultimate upscale script with same seed:
00001-1924817058_img2img

The highres fix method seem to generate less noisy irrelevant details.

**Comment by huchenlei** [comment]
image

**Comment by huchenlei** [comment]
This feature is also requested in https://github.com/Mikubill/sd-webui-controlnet/issues/2249.

**Comment by huchenlei** [comment]
Direct t2i with tile model, 2x size (1024x1536) and same seed:

00000-1924817058_t2i

Hires result has some slight difference in details, probably because added noise during diffusion process. Conclusion is probably not worth doing tile with hires fix?

**Comment by dark-edgelord** [comment]
I don't see this option at all in the UI anywhere, even with hiresfix enabled.

**Comment by huchenlei** [comment]
You need A1111 1.7.0+ for the UI to work properly.

**Comment by dark-edgelord** [comment]
I have that, but I found out what the issue is. It only shows up when clicking the hires fix check box, not the accordion (that also ticks the box automatically).

image

Clicking green works, red doesn't.

**Pull request merged**
