### PR TITLE
Added support for Multi-ControlNet (list notation).

### PR DESCRIPTION
**Pull request by aiton-sd**
### Example:
- any = [any, any, any, ...]
- [any] = [any, None, None, ...]
- [None, None, any] = [None, None, any]
- [,,any] = [None, None, any]
- any, [,any,] = [any, any, any, ...], [None, any, None]

> Enabled Only:

- any = [any] = [any, None, None, ...]

### Note:

- Whitespace characters are replaced with None.
- The configuration values that correspond to the None index are used from GradioUI.
- There is a difference in behavior between 'Enabled' items and non-'Enabled' items when using 'any' (not in a list).
- Using [] in the filename will cause it to malfunction. Only the [hash value] is allowed.

### CODE REVIEW

**Comment by Mikubill** [comment]
Looks good! Could you add some examples about how to apply different x/y/z to multi-controlnet configuration?

**Comment by aiton-sd** [comment]
### Others Enabled
| XYZ Values             | Count | CN0         | CN1         | 
| ---------------------- | ----- | ----------- | ----------- | 
| None                   | 1     | UI          | UI          | 
| 2                      | 1     | 2           | 2           | 
| [2]                    | 1     | 2           | UI          | 
| [2, None]              | 1     | 2           | UI          | 
| [None, 2]              | 1     | UI          | 2           | 
| [, 2]                  | 1     | UI          | 2           | 
| [1, 2], [3, 4], [5, 6] | 3     | 1 / 3 / 5   | 2 / 4 / 6   | 
| None, [2], [, 2]       | 3     | UI / 2 / UI | UI / UI / 2 | 
### Enabled Only
| XYZ Values                | Count | CN0        | CN1           | 
| ------------------------- | ----- | ---------- | ------------- | 
| True                      | 1     | True       | UI            | 
| [True]                    | 1     | True       | UI            | 
| [None, 1], [True, true]   | 2     | UI / True  | True / True   | 
| [None, 0], [False, false] | 2     | UI / False | False / False |

**Comment by marcsyp** [comment]
This is great -- I _think_ I understand the examples, but I'm a bit confused about what "Others Enabled" and "Enabled Only" mean.  Can you elaborate?  Also, what happens if I have CN-0 and CN-2 enabled, do I still provide an array of two values, or do I need to add a blank (e.g., [0,,2])?  Thanks!

**Comment by marcsyp** [comment]
So I have been testing and there appear to be bugs -- following the [1, 2], [3, 4], [5, 6] pattern but with preprocessor resolution, I use:

[500, 500], [505, 505], [510, 510], [515, 515], [520, 520], [525, 525]

I do indeed get 7 images, but the last 5 images are nearly identical to image 2, which can be confirmed not to be the case when simply using the UI to set resolutions.

Also, I would expect there to be a syntax similar to standard syntax to handle ranges.  For instance, I have two preprocessers, and I want to test multiple resolutions between a range.  I might do:

[400-500, 600-700][11]  // results in 11 images at [400, 600], [410, 610], [420, 620]...
[400-500, ][11]  // results in 11 images at [400, UI], [410, UI], [420, UI]...
[400-500, 700-600][11]  // results in 11 images at [400, 700], [410, 690], [420, 680]...
[400-500, 600][11]  // results in 11 images at [400, 600], [410, 600], [420, 600]...

Also, there could be a way to add combinatorial ranges, where every possibility is created.  This could be done by simple leaving out the outer brackets and using range brackets for individual controlnets and leverages the standard syntax from webui:

600-700[11], 200-250(+10)  // results in a 11 x 6 grid with [600, 610, ... , 700] in X and [200, 210, ... , 250] in Y

Thoughts?

**Comment by marcsyp** [comment]
My first thought after writing that is that the last example I gave allows for n-dimensional grids , which may not be a great idea.  :)  Maybe it only supports up to 3 ranges, and can't be used with other Y and Z controls in the X/Y/Z script...

**Comment by marcsyp** [comment]
One additional thought -- debugging this is actually fairly difficult, because there is no preprocessor resolution or thresholds stored in the PNG data, so it is difficult to see how the X/Y/Z script is actually interpreting the values.  Referencing the following issue:

https://github.com/Mikubill/sd-webui-controlnet/issues/399#issue-1600272521

**Comment by aiton-sd** [comment]
> This is great -- I _think_ I understand the examples, but I'm a bit confused about what "Others Enabled" and "Enabled Only" mean. Can you elaborate? Also, what happens if I have CN-0 and CN-2 enabled, do I still provide an array of two values, or do I need to add a blank (e.g., [0,,2])? Thanks!

If you input 'any' for items other than [ControlNet] Enabled, it will be applied to all ControlNets with Enabled checked on the UI. This is the same as inputting [any, any, any, ...].

If you input 'any' for [ControlNet] Enabled, it will override the Enabled value of Control Model - 0. This is the same as inputting [any].

So, if you want to apply Weight changes to CN0 and CN2 which are enabled on the UI, you should input 'any' or [any, , any]. If you want to control the Enabled of CN0 and CN2 with X/Y/Z plot, you need to input [any, , any].

**Comment by marcsyp** [comment]
Sorry, I'm having a really hard time understanding -- what do 'any' and 'None' refer to exactly?  I'm not sure if you are saying that my examples above were not correct, or... ??  Maybe it's worth you posting some real-world examples of how the syntax is used, with demostrated use cases with the UI and actual X/Y/Z commands that result in successful grids?  I guess the more I read the comments on this thread the less I think I understand...  I'm beginning to think I must be missing some key knowledge that others are more familiar with, or maybe I am trying to use this for a purpose it was not intended for.  Thank you!

**Comment by BugMonkey42335** [comment]
I think I have managed to figure this system out. We're comparing are two variables on a single ui axis and you have to manually enter every possible combination. Good luck to anyone trying to compare more than two values.

**Comment by marcsyp** [comment]
Yes but even this doesn't work properly, see [comment above](https://github.com/Mikubill/sd-webui-controlnet/pull/407#issuecomment-1451133014).

**Comment by marcsyp** [comment]
P.S. I really appreciate all the work that everyone is putting into this project -- just trying to help the development on what will be a really awesome and critical feature for fine-tuning parameters.  Thanks all.

**Comment by marcsyp** [comment]
OK, apologies, a correction -- the notation for multiple passes is indeed working as described above -- my test was for very small increments in preprocessor resolution that do not have a large impact on the image result, and so I was incorrectly assuming that the list processing had failed.  Further test with larger increments do in fact work properly.

Regardless, my comments above regarding the processing of a syntax to automatically generate lists are still valid.  It would be great to be able to define an explicit number of pairings using something like:

 [400-500, 600-700][11] // results in 11 images at [400, 600], [410, 610], [420, 620]...
[400-500, ][11] // results in 11 images at [400, UI], [410, UI], [420, UI]...
[400-500, 700-600][11] // results in 11 images at [400, 700], [410, 690], [420, 680]...
[400-500, 600][11] // results in 11 images at [400, 600], [410, 600], [420, 600]...

In the meantime, I will simply be writing code to generate the text pairs spelled out the way I want them and copy paste those values into the field.  Thanks.

**Pull request merged**
