### PR TITLE
Update batch_hijack.py

### PR DESCRIPTION
**Pull request by apsntian**
change the comparison method of InputMode 

I'm modifying the webui code to use controlnet+adetailer as rest api, I found that this code causes problem. 

The problem is the class variable of InputMode is instantiated for each thread (UI and Rest API), so the comparison from Rest API doesn't work properly. In Python, it is not regarded as string, so the comparison is done with their id.  so I changed the comparison code into just simple string comparison.

### CODE REVIEW

**Comment by huchenlei** [comment]
I don’t think it is because different thread will reinitialize the variable. This is a module reload problem similar to ControlNetUnit issue we had earlier. 

The comparison fail is also not because of ID comparison. It’s because the new class of input mode is different from the old input mode class.

If input mode is constructed within ControlNet’s scope, we should find a place to do proper module reload instead of comparing string values.

Note: a1111 has claimed to do the proper module reloading now after 1.4.0. Should we get rid of all module reload code so they don’t cause us troubles?

@ljleb @lllyasviel

**Comment by ljleb** [comment]
These double definitions are a bit annoying.

> Note: a1111 has claimed to do the proper module reloading now after 1.4.0. Should we get rid of all module reload code so they don’t cause us troubles?

I think this is fine. The reload button in the extensions tab was also replaced by "apply and quit".

As we don't need to reload the modules now, a fix is to move all definitions of external_code.py to another file, i.e. internal_controlnet/external_code.py and then import * from that file. This should ensure that module caching from python will work properly.

**Comment by ljleb** [comment]
@apsntian can you verify that #1775 fixes the issue? It has been merged in main just now.

**Comment by apsntian** [comment]
> @apsntian can you verify that #1775 fixes the issue? It has been merged in main just now.

I checked that #1775 fixes my issue.  Thanks a lot!

**Pull request closed without merging**
