### PR TITLE
fix: do not assume images in postprocess_batch is a tensor

### PR DESCRIPTION
**Pull request by ljleb**
In sd-webui-comfyui we need `images` to be a list, so that each image in the list can have an arbitrary size, and so that the list size can change arbitrarily. It seems that `len(tensor)` is defined and equivalent to `tensor.shape[0]`.

See https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11933 for details.

### CODE REVIEW

**Comment by ljleb** [comment]
It seems that `len(tensor)` has been a thing for a long time:

https://github.com/pytorch/pytorch/blame/e3539a0e5497677a0f7ef29dc8278d249bbccb43/torch/_tensor.py#L907

This should then work no matter which version of python is installed.

**Review by huchenlei — APPROVED** [review]
LGTM

**Comment by ljleb** [comment]
Thanks!

**Comment by huchenlei** [comment]
Np. The PR passes web tests so I am confident that it does not break anything major. Also, can you take a look at #1802? I am not very familiar with ADetailer, but from the source code ADetailer is not trying to import anything directly from ControlNet. Why the behaviour changes after reload got removed?

**Comment by ljleb** [comment]
Sure I'll look into it.

**Pull request merged**
