### PR TITLE
Remove deprecated api

### PR DESCRIPTION
**Pull request by ljleb**
Remove the deprecated inference API routes. Discussion: #1132

### CODE REVIEW

**Comment by ljleb** [comment]
raised the api version as well since this is a breaking change.

**Comment by lllyasviel** [comment]
will this break ci test? do we remove old tests?

**Comment by ljleb** [comment]
no it does not break ci tests, as I could not find any test for the deprecated api routes.

**Comment by ljleb** [comment]
The failing pipeline above is because I manually cancelled it.

**Comment by lllyasviel** [comment]
but what are those test_deprecated_xxx?

**Comment by lllyasviel** [comment]
what is TestDeprecatedTxt2ImgWorking?

**Comment by ljleb** [comment]
It's for flattened args. We used to be able to pass all args as a flattened list instead of a list of dicts. We can remove this feature as well, we do not need it anymore and I don't think anyone is using it in this case.

**Comment by lllyasviel** [comment]
do it

**Pull request merged**
