### PR TITLE
try fix strange apple problem

### PR DESCRIPTION
**Pull request by lllyasviel**

### CODE REVIEW

**Comment by lllyasviel** [comment]
https://github.com/Mikubill/sd-webui-controlnet/issues/907

**Comment by blobbfobb** [comment]
Thank you for the extension and the quick bug fix!

I haven't tried all models, but Canny, OpenPose, and Depth Midas now work fine. Depth Leres fails with the following Terminal output:

`Traceback (most recent call last):
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/bobafett/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 401, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "/Users/bobafett/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 174, in leres
    results = model_leres(img, thr_a, thr_b)
  File "/Users/bobafett/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/leres/__init__.py", line 83, in apply_leres
    depth = estimateleres(input_image, model, width, height)
  File "/Users/bobafett/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/leres/leres/depthmap.py", line 43, in estimateleres
    prediction = model.depth_model(img_torch)
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/bobafett/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/leres/leres/multi_depth_model_woauxi.py", line 32, in forward
    lateral_out = self.encoder_modules(x)
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/bobafett/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/leres/leres/network_auxi.py", line 96, in forward
    x = self.encoder(x)  # 1/32, 1/16, 1/8, 1/4
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/bobafett/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/leres/leres/Resnext_torch.py", line 223, in forward
    return self._forward_impl(x)
  File "/Users/bobafett/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/leres/leres/Resnext_torch.py", line 199, in _forward_impl
    x = self.conv1(x)
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/bobafett/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 319, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/bobafett/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (MPSFloatType) and weight type (torch.FloatTensor) should be the same`

**Comment by lllyasviel** [comment]
some preprocessors may not support amd or mac. it is impossible to fix. please use other alternative preprocessors

**Comment by blobbfobb** [comment]
@lllyasviel I see. Thank you!

**Comment by AlanZhou2022** [comment]
Alright, I see why controlnet cannot work on my Mac, hope the problem can be fixed in the near future.

**Pull request merged**
