### PR TITLE
[WIP] AnimateDiff V2.0.0 ControlNet Part

### PR DESCRIPTION
**Pull request by continue-revolution**
- [ ] https://github.com/continue-revolution/sd-webui-animatediff/pull/381

### CODE REVIEW

**Comment by bruce55** [comment]
Tested RGB sparsectrl with the model file in your HF repo, seems to be working quite nicely!
Original photo from Unsplash:
photo-1557408938-0f220f49bca1

RGB Sparsectrl to frame 0:


A side issue caused by util code moved from animatediff:
On my side, when testing with the latest commit, uploaded videos for CN could not be extracted due to invalid path.
https://github.com/Mikubill/sd-webui-controlnet/blob/cba991bdf8bddf43655880d5238c07f523afe6d7/scripts/utils_animatediff_cn.py#L82C5-L86C1

The `video_path` passed to the two extraction function is something like `D:\{path_to_webui}\tmp\animatediff-framesC:\{path_to_gradio_tmp_upload}-{hash}` , notice the drive letter `C:` from `params.video_source` appended to the path.

**Comment by huchenlei** [comment]
@continue-revolution

Are you still actively working on this? I can probably take over the implementation if you don't have time.

**Comment by continue-revolution** [comment]
yes. I've almost done magic animate but not tested

**Comment by continue-revolution** [comment]
We are moving changes to #2661 which I have almost finished.

**Pull request closed without merging**
