### PR TITLE
update model_list to allow to set whether to update model

### PR DESCRIPTION
**Pull request by LeonZhao28**
add a parameter in the method `/controlnet/model_list` to allow user to set whether to update model

### CODE REVIEW

**Comment by huchenlei** [comment]
Generally, a get request should not have side effect on the server. If you want an option to refresh model_list using web API, I would suggest adding a new POST endpoint.

**Comment by LionelZhao28** [comment]
> Generally, a GET request should not have side effect on the server. If you want an option to refresh model_list using web API, I would suggest adding a new POST endpoint. 

Yes, I agree. But I actually hope to not reload the local model list every time I call this api. The change I pushed is actually to ensure consistency with existing Api usage. From an interface design perspective, it is not reasonable to force a refresh of the local model list. So, do you think it's better to keep the current habit of not changing the small-scale optimization API, or to make it more reasonable but lacking it will affect the usage of the existing API?

**Comment by huchenlei** [comment]
Sorry I missed the context. Currently we are doing the refresh everytime the API is called. From that perspective, I think your change is reasonable. We should not break the API consistency without collecting metrics, as users might depend on existing behaviour.

Thanks for spotting the issue and fix it.

**Review by huchenlei — APPROVED** [review]
LGTM

**Pull request merged**
