### PR TITLE
Added  a new API call to get the preprocessor list

### PR DESCRIPTION
**Pull request by mishafarms**
In order to not have to hard code the modules in code that uses the API, it seemed easy to request the list of modules that
can be set.

### CODE REVIEW

**Comment by mishafarms** [comment]
Merged and updated my code.

**Comment by scruffynerf** [comment]
Thanks for ensuring the external_code got this as well.  +1

**Comment by ljleb** [comment]
I moved the preprocessor+unloadable dicts directly to `global_state`, otherwise LGTM.
Thanks for your contribution!

**Comment by ljleb** [comment]
@mishafarms Sorry to have to ask this, I would appreciate if you could add your changes in a new PR. I think I don't want to try merging code into main anymore :x

**Pull request merged**
