### PR TITLE
feat: significantly accelerates detectmap_proc performance

### PR DESCRIPTION
**Pull request by storyicon**
I found that with the change to the master branch, there were some conflicts with the previous commit https://github.com/Mikubill/sd-webui-controlnet/pull/1416. I made some adjustments and recommitted this optimization.

### CODE REVIEW

**Comment by storyicon** [comment]
I found in my testing that the optimization it brings is in some cases more obvious than turning on xformers, close to about 1s of optimization can save some companies a lot of graphics card costs, I think it is an effective optimization. @lllyasviel

**Comment by storyicon** [comment]
cc:  @Mikubill

**Comment by JulianVolodia** [comment]
I testing this for more than week. It works well for me. I merged into my fork your work. Thanks @storyicon for this! :)

**Comment by huchenlei** [comment]
From https://github.com/Mikubill/sd-webui-controlnet/issues/1648 we know that `detect_map` can take long when processing large images. 2s for 3k x 2k image. 

@lllyasviel We should consider merging this to alleviate the issue.

**Comment by lllyasviel** [comment]
I will take a look at this and hopefully this weekend. Hopefully it will not cause strange problems on mac and ndarray contiguous

**Comment by lllyasviel** [comment]
Also how reliable is our unit test system now? Does passing unit test really means the test are passed with all assets succeed? cuz I remember a period of time someone says some errors will be hidden by the github ci

**Comment by ljleb** [comment]
One thing that makes tests unreliable is that they are run on an old version of the webui.

AFAIK you are referring to web api tests that resulted in hidden failures, which should have been resolved by testing for the presence of the string "ERROR" in the logs.

**Comment by huchenlei** [comment]
> One thing that makes tests unreliable is that they are run on an old version of the webui.
> 
> AFAIK you are referring to web api tests that resulted in hidden failures, which should have been resolved by testing for the presence of the string "error" in the logs.

I think we are only checking string "error" in stderr. The log messages ControlNet emitts are all on stdout. I think following error is triggered in our API tests but ignored:
```
        if os.path.exists(override_config):
            network_config = override_config
        else:
            # Note: This error is triggered in unittest, but not caught.
            # TODO: Replace `print` with `logger.error`.
            print(f'ERROR: ControlNet cannot find model config [{override_config}] \n'
                  f'ERROR: ControlNet will use a WRONG config [{network_config}] to load your model. \n'
                  f'ERROR: The WRONG config may not match your model. The generated results can be bad. \n'
                  f'ERROR: You are using a ControlNet model [{model_stem}] without correct YAML config file. \n'
                  f'ERROR: The performance of this model may be worse than your expectation. \n'
                  f'ERROR: If this model cannot get good results, the reason is that you do not have a YAML file for the model. \n'
                  f'Solution: Please download YAML file, or ask your model provider to provide [{override_config}] for you to download.\n'
                  f'Hint: You can take a look at [{os.path.join(global_state.script_dir, "models")}] to find many existing YAML files.\n')
```

**Comment by ljleb** [comment]
> I think we are only checking string "error" in stderr.

That is true, and it could be a problem for errors that are printed to stdout. Maybe add file=sys.stderr for these prints?

I am not sure if testing for "error" in stdout could result in false failures? Maybe not. If not, verifying the content of stdout would work I think.

**Comment by huchenlei** [comment]
For reference: #1541 has detailed error message

**Comment by ljleb** [comment]
The truth is, reading console output to determine test failure is a hack. There should be a better way to do this. If it's out of the control of extensions, an issue needs to be raised on a1111 webui.

IIUC a proper fix could be to allow to disable extension error catching from a1111 webui code with a setting. I think I'll open an issue for that.

**Comment by storyicon** [comment]
> I testing this for more than week. It works well for me. I merged into my fork your work. Thanks @storyicon for this! :)

I'm glad to hear that and happy to be able to contribute to the controlnet community.

**Comment by huchenlei** [comment]
The PR passes web_tests locally. Going to merge it. If it breaks anything platform specific, feel free to revert it.

**Pull request merged**
