### PR TITLE
[1.1.412] Second round of workloads for community XL control models

### PR DESCRIPTION
**Pull request by lllyasviel**
This workload contains some more recent XL community control models.
This will mainly related to new ip-adapters and lllite controls.
For sd 1.5, a previous missing recoloring controlnet will be added then.
Other control models like controlnet XS is under investigation - if not added in this second round, then we will have a third round.
This workload will also include several bug fixes to sd-webui-controlnet 1.1.4

### CODE REVIEW

**Comment by lllyasviel** [comment]
If anyone know some bugs should be fixed with highest priority, please take a note here by replying this

**Comment by huchenlei** [comment]
Probably not related to the new models support, but https://github.com/Mikubill/sd-webui-controlnet/issues/2148 is a known issue that is both reproducable and worth fixing.

**Comment by kft334** [comment]
> If anyone know some bugs should be fixed with highest priority, please take a note here by replying this

Using any ip-adapter with only masked does not produce good results. Perform this experiment with both 'Whole image' and 'Only masked': Using image-to-image, mask a face, set ControlNet start to 25% and observe how the face changes at 25% of steps. You'll see an abrupt and dramatic change and very good likeness with 'Whole image' but a very weak change and poor likeness with 'Only masked'. I can reproduce this 100% of the time.

**Comment by BrickMissle** [comment]
When "Show batch images in gradio gallery output" in unselected in settings, it still shows the batch images anyways. It's not a major bug but I figured I'd point it out here in case it's easily fixable or something dumb on my end and not worth making a PR

**Comment by sdbds** [comment]
https://github.com/Mikubill/sd-webui-controlnet/discussions/2127
hope to support this preprocesser.

https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite
add some new controlnet lllite

**Comment by SpenserCai** [comment]
Hop to support this:
#2166 

https://huggingface.co/h94/IP-Adapter/blob/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.bin

**Comment by rabidcopy** [comment]
Would it be possible to support passing multiple inputs to IP-Adapter? (not a batch to be processed one by one) A very neat thing in ComfyUI right now is being able to pass multiple images of a subject or style to help the final result be more varied and less like an img2img pass. Or it can be used to mix styles and concepts simultaneously.
https://civitai.com/articles/2345/aloeveras-instant-lora-no-training-15-read-new-info
https://www.youtube.com/watch?v=HtmIC6fqsMQ
https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by huchenlei** [comment]
> Would it be possible to support passing multiple inputs to IP-Adapter? (not a batch to be processed one by one) A very neat thing in ComfyUI right now is being able to pass multiple images of a subject or style to help the final result be more varied and less like an img2img pass. Or it can be used to mix styles and concepts simultaneously. https://civitai.com/articles/2345/aloeveras-instant-lora-no-training-15-read-new-info https://www.youtube.com/watch?v=HtmIC6fqsMQ https://github.com/cubiq/ComfyUI_IPAdapter_plus

What would be the difference between this feature and using multiple IP-Adapter ControlNet units?

**Comment by rabidcopy** [comment]
> > Would it be possible to support passing multiple inputs to IP-Adapter? (not a batch to be processed one by one) A very neat thing in ComfyUI right now is being able to pass multiple images of a subject or style to help the final result be more varied and less like an img2img pass. Or it can be used to mix styles and concepts simultaneously. https://civitai.com/articles/2345/aloeveras-instant-lora-no-training-15-read-new-info https://www.youtube.com/watch?v=HtmIC6fqsMQ https://github.com/cubiq/ComfyUI_IPAdapter_plus
> 
> What would be the difference between this feature and using multiple IP-Adapter ControlNet units?

Wouldn't the latter being loading the ControlNet multiple times and wasting resources and compute? Also when I tried doing that it error'd out.

**Comment by huchenlei** [comment]
Thanks for the feedback. I thought lvmin implemented the logics in https://github.com/Mikubill/sd-webui-controlnet/pull/1952/commits/e4e58078b03f3f3e146162728117846394ad4b70, but obviously it is not working properly. Can you file a separate issue to track this problem?

**Comment by sdbds** [comment]
https://github.com/Fannovel16/comfyui_controlnet_aux/pull/71

i met same error for  torch 2.1,numpy.int is another class.

i recommend change it for updating.

**Comment by George0726** [comment]
Could you mind support the ControlNet-XS models?
ControlNet-XS: https://github.com/vislearn/ControlNet-XS

**Comment by lllyasviel** [comment]
image
These models are all tested and now they all works.
The workload is a bit heavy and let us have other rounds for other issues.
However, these may be more important so lets just merge here first.

**Comment by lllyasviel** [comment]
help on some other tasks are also welcomed.

**Comment by sdbds** [comment]
> help on some other tasks are also welcomed.

i had finished my tasks in this list, hope to review soon.

#2211 #2212

**Pull request merged**
