### PR TITLE
fix img2img batch generation

### PR DESCRIPTION
**Pull request by ddPn08**
The solution for #46 .

Add Batch generation checkbox to prevent detection_map from being added to `result`.
This is the process because I couldn't find the variable that determines whether it is batch processing from the pipeline.

### CODE REVIEW

**Comment by Mikubill** [comment]
Added in settings panel: https://github.com/Mikubill/sd-webui-controlnet/commit/4b26a6d6591af3ebc400f70bd1c2cd9451c91646

**Comment by vjsaw** [comment]
If you dont put in an output path, just leave it blank, and let it write in the image2image folder. That works for me.  Before I tried to edit the controlnet.py manually, but after CN doesnt showed up any longer in ui. 😂  Im back to  the original controlnet.py file and leave the output blank. Solution for now 🙂

**Comment by ljleb** [comment]
IIUC, this is related to https://github.com/Mikubill/sd-webui-controlnet/discussions/111#discussioncomment-5000214
> In settings tab, tick the "Do not append map to output" checkbox.

**Comment by Verte71** [comment]
thanks guys "Do not append map to output" works for batch, but it stopped rendering these maps/additional images that are really helpful, and even when i switched it back by unchecking "Do not append map to output" it doesn't work. Any tip to get them back to appear?

**Comment by ljleb** [comment]
@Verte71 as of latest version the code will automatically remove the detectmap when in batch mode. you can now update the extension and safely uncheck the option in the settings.

**Pull request closed without merging**
