### PR TITLE
Add Weight item to X/Y/Z plot

### PR DESCRIPTION
**Pull request by aiton-sd**

### CODE REVIEW

**Comment by demirklvc** [comment]
@Mikubill hey! ive updated but still cant see it in the X/Y/Z script-or is it not implemented yet?

**Comment by Mikubill** [comment]
Maybe you should restart your WebUI to enable this script.

**Comment by demirklvc** [comment]
Bildschirmfoto 2023-02-17 um 16 09 17
@Mikubill

**Comment by demirklvc** [comment]
can you please help me to fix this

**Comment by Mikubill** [comment]
Update extension and restart webui will fix it.

**Pull request merged**
