### PR TITLE
[New Feature] Allow user to download openpose preprocessor result as JSON file

### PR DESCRIPTION
**Pull request by huchenlei**
This PR adds a link on the page to allow user to download openpose preprocessor result as JSON file.

The link only appears when:
- `Allow Preview` option is checked
- An openpose related model is selected
- Trigger button on preprocessor is clicked

The link will not disappear unless the preprocess is clicked again and another preprocessor is selected.

The JSON file format follows [openpose repo's output format](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md).

demo

This is the first step to build an seamless integrated openpose editor(#1012). I will do some research on how to send the JSON to another extension and how to set the preprocessor image in controlnet.

### CODE REVIEW

**Comment by lllyasviel** [comment]
rightnow you can already get pose meta rather than pose image by return_is_index=True
https://github.com/Mikubill/sd-webui-controlnet/blob/2bc4400011b38ab7f1d3f27a95897a6cb0c28c2a/annotator/openpose/__init__.py#L120
you can simply json.encode(pose) without external codes

**Comment by huchenlei** [comment]
There are several problems with current metadata:
- Hand/Face ownership is not specified
- Need index lookup for desired keypoint
- Does not conform with the [openpose repo's output format](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md).

#1077 was submitted to address all problems. We can probably discuss more there.

**Comment by huchenlei** [comment]
Reworked the button style to make it match overall gradio app style:

demo2

**Comment by lllyasviel** [comment]
are u willing to join repo collaborator? it seems that we also have some system ram leak problem of preprocessors and perhaps we want more people to take a look

**Comment by huchenlei** [comment]
Sure I can join the repo collaborator. Are we talking about memory leak #990?

**Comment by lllyasviel** [comment]
well let me tell mikubill

**Comment by lllyasviel** [comment]
ok i told mikubill. lets see when he revives. Also u need to join the repo to get those parts merged since your modifications are large and u need to be able to maintain this part if anything went wrong

**Comment by huchenlei** [comment]
I received the repo collaborator invitation. Should I assign someone to review the chain of PRs?

**Comment by lllyasviel** [comment]
> I received the repo collaborator invitation. Should I assign someone to review the chain of PRs?

test in another branch and merge if you think everything ok

**Comment by lllyasviel** [comment]
dont forget to edit https://github.com/Mikubill/sd-webui-controlnet/blob/main/scripts/controlnet_version.py when you feel you are done

**Pull request merged**
