### PR TITLE
[New Feature] Integrated Openpose Editor

### PR DESCRIPTION
**Pull request by huchenlei**
#1012 proposed an integrated openpose editor. Months passed, we are finally close to have one. 

Screen Capture 001 - Stable Diffusion - localhost
Screen Capture 003 - Stable Diffusion - localhost

Workflow of this feature:
[screen-capture.webm](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/6ff02650-69a8-4546-92ea-92021f8a9ff1)

There are still a few things that need to be worked out though:

### How should the edited image be used by controlnet?
#1211 Discussed why we cannot make the preview result directly used by controlnet. TLDR is that many preprocessors use values from WebUI that are only available when clicking the generate button.

Option1: Let controlnet use pre-rendered openpose image if there is an update-to-date one. (Make an exception for openpose only as openpose preprocessor does not depend on any WebUI runtime values) 
Option2: Add a button to push the preprocessor result to the input image and select none for preprocessor. This option is not so ideal as once sent, the pose becomes uneditable.

### How should we release this feature to the users. 
Behind the scene, the feature is embedding an openpose editor web page in an iframe. The controlnet JS code communiates with the iframe web page via `window.postMessage`. Currently this requires user install https://github.com/huchenlei/sd-webui-openpose-editor/tree/main separately.

If the extra extension is not installed, how should we handle the prompting:
Option1: Install the extension in the background. (Maybe too agressive?)
Option2: Display a line of text let user know the feature need another extension to function.

### CODE REVIEW

**Comment by lllyasviel** [comment]
wow great. how can js send data to gradio? what is the currently used method?

**Comment by huchenlei** [comment]
> wow great. how can js send data to gradio? what is the currently used method?

There is a hidden gr.Textbox that accepts pose JSON from JS code. 
https://github.com/gradio-app/gradio/issues/2981 explains how to formulate an event so that gradio backend can recognize data update on gr.Textbox. (Not surprising that the issue was raised by AUTOMATIC1111 lol)

**Comment by lllyasviel** [comment]
wow sounds very a1111. will take a look soon

**Comment by 2blackbar** [comment]
This is pretty great, is there a way to have a button to make entire hand and bones appear instead of enabling bones one by one ?

**Comment by huchenlei** [comment]
> This is pretty great, is there a way to have a button to make entire hand and bones appear instead of enabling bones one by one ?

Yes, you can toggle visibility on entire hand, body, face. But invalid/missing keypoints are marked invisible by default, so if there are invalid keypoints, they are likely to be jammed at the same location.

I am working on the documentation on the editor repo. Hopefully that will clarify things.

**Comment by lllyasviel** [comment]
image

**Comment by huchenlei** [comment]
> image

Need to install https://github.com/huchenlei/sd-webui-openpose-editor/tree/main first. (No need to build now as it automatically pull latest release binary from GitHub.)

**Comment by huchenlei** [comment]
Screen Capture 004 - Stable Diffusion - localhost
Screen Capture 005 - Stable Diffusion - localhost

Now we display a error screen to guide user if no editor is detected.

**Comment by huchenlei** [comment]
I think I now have answers to the 2 questions originally asked:
### How should the edited image be used by controlnet?

Option2: Add a button to push the preprocessor result to the input image and select none for preprocessor. 
Note: Option1 takes too much effort to implement and might cause confusion to users.

### How should we release this feature to the users?
Option2: Display a line of text let user know the feature need another extension to function.

This PR is now ready to be merged.

**Comment by lllyasviel** [comment]
or perhaps we just add a dirty flag to preview image. if sha256 of a input image match some marked sha256 then replace it with another image before processing. maintain a sha to ndarray dict

**Comment by huchenlei** [comment]
> or perhaps we just add a dirty flag to preview image. if sha256 of a input image match some marked sha256 then replace it with another image before processing. maintain a sha to ndarray dict

Probably need to hash all the input settings (resolution, etc) used to generate the preview image instead of just the hash of input image. I think for now a "Send back" button is the most cost efficient solution.

**Comment by lllyasviel** [comment]
then user click two buttons,first a button from extension and then send back?

**Comment by lllyasviel** [comment]
i think i can try it a bit tomorrow or later soon. how big is that extension? is it possible to directly move into cn, or hide the button if extension not installed?

**Comment by huchenlei** [comment]
> i think i can try it a bit tomorrow or later soon. how big is that extension? is it possible to directly move into cn, or hide the button if extension not installed?

The extension is not too big. 2~3k lines of typescript code. The problem is that the extension is need to be build with nodeJS installed. My current workaround is to let user pull the compiled app from github release. If we include the editor in this repository, it is likely to messup the release page. 

I can add an option in settings to hide the edit button, and prompt the user to go to settings and toggle that option if they don't want to see an edit button with alert sign.

**Comment by huchenlei** [comment]
> then user click two buttons,first a button from extension and then send back?

When the user is satisfied with the image in the preview, the user can click `Send back` button to use the preview image as input image.

Overall workflow:
1. Click edit to pop up the editor modal
1. Do the necessary edits
1. Click `Send to ControlNet` in the editor modal to close the editor
1. Repeat step#1 if there are other changes to be made or click `Send back` to use the edited image as controlnet input image

**Comment by huchenlei** [comment]
> it seems when I click a button titled "Send to ControlNet", I will expect that this image will be used by CN. Clicking another button again sounds a bit ... Perhaps I can try later and see if we can find a solution.

We can directly set the input image when clicking send to ControlNet but that would overwrite the input image. If the user decides to adjust the pose again, the original input image won't be available as the background image in the editor. 

The ideal way is let ControlNet use the edited pose in the generated image section, but I found it no so easy to implement.

**Comment by huchenlei** [comment]
@lllyasviel Gentle ping on the review. I can try to implement the logic to use the up-to-date preview image if you think that is the way to go.

**Comment by huchenlei** [comment]
> I am relatively busy this week. I think we can use a branch in this repo or what to test the features, and then perhaps the weekend I can test it more and try to merge hopefully. Since the difference looks big and many users are actively updating this recently, I do not recommend to directly work on main branch for this.

A new branch `embed_pose_edit` is created.

**Comment by huchenlei** [comment]
Hi @lllyasviel,

Can you take a look again? I add a new checkbox to allow direct usage of preview image as controlnet input.

Now the workflow is reduced to:
1. Click edit to pop up the editor modal
1. Do the necessary edits
1. Click Send to ControlNet in the editor modal to close the editor
1. Click genereation to run SD or go back to Step 1 to do more edits

**Comment by huchenlei** [comment]
I am going to merge this if no further oppositions / feedbacks are received. 

Some testings:
- Edit / Remove person 
[edit_demo.webm](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/21189d24-050e-4ad3-bdec-d05440799c92)
- Disable feature
[feature_off_demo.webm](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/977d4e41-1be7-4b2a-b389-82115ccd3213)

We can either make the feature disabled by default or revert this PR if the user feedback is really negative.

**Comment by continue-revolution** [comment]
1. It would be better if you could add a feature where people could directly add and edit pose, without any reference image.
2. It would be better if people do not have to build front end stuff. This is especially painful for non-experts like me.

**Comment by huchenlei** [comment]
> 1. It would be better if you could add a feature where people could directly add and edit pose, without any reference image.
> 2. It would be better if people do not have to build front end stuff. This is especially painful for non-experts like me.

1. The feature can be accessed directly in `localhost:7860/openpose_edit_index`. The default will not include hand/face.
2. People don't need to build front-end stuff as the extension downloads the compiled app zip from github release.

**Comment by huchenlei** [comment]
Also from the demo there is an issue with the openpose detection: The same hand got detected twice on the right person. Going to open an issue for this.

**Pull request merged**
