### PR TITLE
Update model dropdown choices when sd checkpoint change

### LINKED ISSUE #2270: [DevTask] Update ControlNet model list when SD model changes
See #2267.

Currently the ControlNet model list will be outdated when SD model changes. We need to trigger an update when SD model changes in A1111.

### PR DESCRIPTION
**Pull request by huchenlei**
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2494.
Closes #2270.

This PR adds the callback when sd checkpoint config. When it changes, model choices will be updated to match the current sd version.

This PR also does a large refactoring to delay register of callbacks after all A1111 component that we use/care have been initialized.

Local testing has verified that following features are still are working:
- [x] loopback checkbox visibility
- [x] batch dir sync
- [x] hr_option visibility
- [x] crop input image visibility
- [x] setting sd model checkpoint
- [x] send dimensions

### CODE REVIEW

**Comment by emorris00** [comment]
Seems there are 2 problems with this. The first is that the callbacks don't get re-registered when the UI is reloaded using the Reload UI button. Second is that the sd checkpoint change updating the models dropdown only works when the 'Checkpoint dropdown: use filenames without paths' setting is set.

**Comment by huchenlei** [comment]
@emorris00 
Thanks for spotting these issues! I have fixed the first UI reload issue. For the second issue, I cannot reproduce it. I do not have `Checkpoint dropdown: use filenames without paths` config enabled, but still checkpoint change indeed cause model list to update (You need to select any control type other than "All").

**Comment by emorris00** [comment]
@huchenlei I have the open pose control type selected. When I don't have that setting set the change event fires immediately when the checkpoint dropdown is changed but the checkpoint hasn't actually changed yet so the model dropdown gets filtered base on the previous checkpoint. When the setting is selected it still does that, but then the change event get fired again after the checkpoint actually changes (the checkpoint name in the dropdown is changed to include the extension) so it then filters correctly based on the current checkpoint. I disabled all extensions except this and running on windows 11 with python 3.10.11.

**Comment by huchenlei** [comment]
Ok, I successfully reproduced the issue. It seems like it only happens if you directly use the dropdown to select checkpoint. If you use the checkpoint tab with thumbnail preview to pick checkpoint, there won't be any issue.

**Pull request merged**
