### PR TITLE
fix controlnet + ultimate sd upscale issue

### PR DESCRIPTION
**Pull request by tfdetang**
try fix https://github.com/Mikubill/sd-webui-controlnet/issues/43

### CODE REVIEW

**Comment by lllyasviel** [comment]
why ultimate sd upscale has anything to do with mask?

**Comment by tfdetang** [comment]
> why ultimate sd upscale has anything to do with mask?
in ultimate sd upscale, the canva size == mask size;  I think the input image size should == canva size == mask size ;   But when I import a control img, it will not resize to canva size which is unexpected

**Comment by lllyasviel** [comment]
what does ultimate sd upscale use mask for? 

and in fact in controlnet if masks exists, then it will enter some inpainting codes.

**Comment by tfdetang** [comment]
> what does ultimate sd upscale use mask for?
> 
> and in fact in controlnet if masks exists, then it will enter some inpainting codes.


Ultimate sd upscale resize image into target size and cut into tiles and mask/blur them; So I think it is make sense to jump into inpainting codes;

**Comment by lllyasviel** [comment]
already fixed with conflicting codes

**Pull request closed without merging**
