### PR TITLE
[New Feature] ControlNet unit preset management

### PR DESCRIPTION
**Pull request by huchenlei**
Users have requested to be able to save easily save and load controlnet unit presets in https://github.com/Mikubill/sd-webui-controlnet/issues/1854.

This PR implements a preset manager UI that allows users to save/load ControlNet unit presets. Presets are persisted locally as text file under `presets/`.

 
Screen Capture 025 - Stable Diffusion - 127 0 0 1

Known issues:
- Preprocessor sliders values are not populated due to issue mentioned in #1833 .
- Toolbuttons are having wrong hover hint.

### CODE REVIEW

**Comment by lllyasviel** [comment]
will you maintain this?

**Comment by huchenlei** [comment]
Hint fixed.

Sure I will be maintaining this part. It is not complex.

**Comment by lllyasviel** [comment]
control type is not stored, make it feel a a bit unpleasant.
Also it should restore blank when controlnet_ui_group.py detects changes. if you get time you may take a look at line 843-872 in controlnet_ui_group.py to see how to implement this

**Comment by huchenlei** [comment]
The design here is that if user make changes with a preset selected, pressing save button will overwrite that preset. To save as a new preset, user need to select new preset and click save.

Going to implement storage of control type later.

**Comment by lllyasviel** [comment]
but if I selected present A and made some changes, how can I go back to A using the present A?
This should be the major use case of preset

**Comment by huchenlei** [comment]
Yea, it can be awkward to select `new preset` and then select `preset A` to clear modifications made.

However, I believe there need to be a way to to edit the preset. Do you think it would be better if we make an edit button and let user edit the raw infostring in a popup box?

**Comment by lllyasviel** [comment]
you may want to design it a bit - and if you think the current form is not mature enough this can be temporarily reverted.
but it is ok if just put here and update it if you move fast

**Pull request merged**
