### PR TITLE
[fix]Adding elem_id to all the gradio component of controlnet

### PR DESCRIPTION
**Pull request by guming3d**
Adding elem_id to all the gradio component of controlnet, we have a extension which use jspath to grap the controlnet component value in DOM, need to set the elem_id otherwise every release will got different jspath.

### CODE REVIEW

**Comment by lllyasviel** [comment]
oh and biggest problem.
when multi controlnet is turned on, if user has N controlnets, you will have N dom element with exactly same elem_id for each name.
The solution is to use prefix. See also how we handle preview_check_elem_id.
This could prevent the pr from merge.

**Comment by guming3d** [comment]
@lllyasviel  what does "when multi controlnet is turned on" mean, can we install multiple controlnet extensions at same time?

**Comment by guming3d** [comment]
BTW, our method to us javascript to grab the controlnet component value is too hack, and easy to fail if jsPath is changed by release. Is there any plan to save the component value to a local js file? Thanks a lot

**Comment by guming3d** [comment]
I have updated the elem_id to use prefix like preview_check_elem_id in the PR, please help to check again

**Comment by lllyasviel** [comment]
> @lllyasviel what does "when multi controlnet is turned on" mean, can we install multiple controlnet extensions at same time?

u can enable multi controlnet in setting

**Comment by huchenlei** [comment]
To avoid conflicted element id, you can set `elem_classes` instead, and using JS query selector to select all elements with certain class, e.g. `document.querySelector(".cnet-canvas-width")`.

**Pull request merged**
