### PR TITLE
Support PuLID

### PR DESCRIPTION
**Pull request by huchenlei**
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2835.

## Overview
[PuLID](https://github.com/ToTheBeginning/PuLID) is an ip-adapter alike method to restore facial identity. It uses both insightface embedding and CLIP embedding similar to what ip-adapter faceid plus model does. However, there is an extra process of masking out the face from background environment using facexlib before passing image to CLIP. PuLID also uses Eva CLIP instead of normal CLIP. In the attn overrides, PuLID also does something more than IPAdapter, as it zero pads the tensor and adds to ortho of hidden states. If you are interested you can read their paper on how this is handled.

image

### Install sd-webui-controlnet-evaclip extension
PuLID uses both evaclip embedding and insightface embedding as proj module input. So in order to use the feature, you need to install https://github.com/huchenlei/sd-webui-controlnet-evaclip extension.
### Download Model
You can download fp16 model here: https://huggingface.co/huchenlei/ipadapter_pulid/resolve/main/ip-adapter_pulid_sdxl_fp16.safetensors
### ControlNet Unit Setting
image
There is an extra radio group to let you select PuLID mode. According to my testing, they only make slight difference, but still something nice to have.

## Example
Input
liuyifei

Output [Fidelity]:
image

Output [Style]:
image

Generation params
```
masterpiece painting, buildings in the backdrop, kaleidoscope, lilac orange blue cream fuchsia bright vivid gradient colors, the scene is cinematic, (1girl:1.2), portrait,, emotional realism, double exposure, watercolor ink pencil, graded wash, color layering, magic realism, figurative painting, intricate motifs, organic tracery, pol
Negative prompt: flaws in the eyes, flaws in the face, flaws, lowres, non-HDRi, low quality, worst quality,artifacts noise, text, watermark, glitch, deformed, mutated, ugly, disfigured, hands, low resolution, partially rendered objects, deformed or partially rendered eyes, deformed, deformed eyeballs, cross-eyed,blurry
Steps: 20, Sampler: Euler a, Schedule type: Automatic, CFG scale: 7, Seed: 3390099943, Size: 1024x1024, Model hash: 31e35c80fc, Model: sd_xl_base_1.0, Clip skip: 2, ControlNet 0: "Module: ip-adapter-auto, Model: ip-adapter_pulid_sdxl_fp16 [d86d05ea], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Threshold A: 0.5, Threshold B: 0.5, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced, Hr Option: Both, Save Detected Map: True", Version: v1.9.3-2-g3d3fc81f
```

### Note
Comparing to instant id, you need stronger prompt to make the output stylized. Following is the same neon style generated by instant id:
300220459-2093167a-6d95-4855-a8cf-4c036f2aefad

### Known issue
facexlib and evaclip in total consumes about 2~3GB of vram. So if you have low vram, that can be an issue. There is also about 500MB of vram not unloaded after unloading the preprocessors. I will need to investigate more on why vram here is not properly freed.

### CODE REVIEW

**Comment by George0726** [comment]
Hi author, thanks for the amazing support!  I am trying to follow your PuLID mode and padding/ orthogonal stuff in code, however, the author seems not illustrating this part in the paper?

**Comment by yanghongquan521** [comment]
EVA02_CLIP_L_336_psz14_s6B   放在哪个文件夹下面

**Comment by maqianzhao** [comment]
EVA02_CLIP_L_336_psz14_s6B 哪里下载？

**Comment by dan4ik94** [comment]
@huchenlei Forge support please

**Comment by prog-ape** [comment]
@huchenlei Forge support please

**Comment by eurotaku** [comment]
@huchenlei
any idea why the previews first show a great representation of the source image and then it falls apart so awfully at the end? played around a bit with the weights and especially block 5 and 6 seem to be responsible for that overburned end result. but they also seem to have the main effect on the reproduction of the person's likeness.

00084-020-3043948951-masterpiece painting buildings in the backdrop kaleidoscope lilac
ken
https://github.com/Mikubill/sd-webui-controlnet/assets/129174287/d5572282-16f7-4df5-ac4d-ef82bd5e27bb

**Comment by Shingkyo** [comment]
P2
P1
Hi, after running 3 single-input image generations and 1 super long 3-input generations. The VRAM is hogged and I cant generate but to terminate and restart. Is there any alternative flush memory extensions or what that can help? P/S: Just a newbie on SD...

**Comment by Shingkyo** [comment]
I see a prompt 'please pip install apex', but this PuLID runs fine without this on WebUI n ComfyUI. I then proceed to install this Apex (Im using Windows), via python setup.py install after git clone this Apex. The previous warning about installing Apex is gone but PuLID cannot run after this and specifically got this warning: [No module named 'fused_layer_norm_cuda'] on my ComfyUI console. The Pytorch is 2.1.2 + CU 11.8. 

I rolled back by uninstalling Apex, and PuLID works again. Im just wondering if a proper Apex actually speeds up the process? If yes, which version shall I install and how shall I do? Im not that tech-savvy and am just an average SD user. Please help... Thanks in advance.

**Comment by sipie800** [comment]
+1, same ugly color blocks happen always

**Comment by wktra** [comment]
No forge, no give a crap.

**Comment by ClothingAI** [comment]
Hello:
1) Does it exist on Forge?
2) Does it work with FLUX please??

**Pull request merged**
