### PR TITLE
Display control type filter as dropdown

### PR DESCRIPTION
**Pull request by missionfloyd**
The control types are starting to take up a lot of space.
Untitled

This adds an option to put them in a dropdown instead.
image

### CODE REVIEW

**Comment by huchenlei** [comment]
See reason why it is not a dropdown: https://github.com/Mikubill/sd-webui-controlnet/pull/1422#issuecomment-1563189096

**Comment by missionfloyd** [comment]
That's why I made it optional.

**Review by huchenlei — APPROVED** [review]
LGTM

**Comment by huchenlei** [comment]
Do note that some JS hacks will be broken if you change it to dropdown:
https://github.com/Mikubill/sd-webui-controlnet/blob/f0a94cb2c448ca4ddce5af11589a072d4c97b1aa/javascript/active_units.js#L74

**Pull request merged**
