### PR TITLE
change annotator paths so that users can remove all when corrupted

### PR DESCRIPTION
**Pull request by lllyasviel**
more and more users complain about that they cannot use some preprocessors.
the reason is that the models are corrupted during downloads.
very disappointing that even if they completely remove controlnet, corrupted models cannot be removed, because they are in webui/models/XXX
all annotators should be in our folder so that in the worst case, users can always delete controlnet and install again to handle all problems.
I am testing it now. will merge when test finish

### CODE REVIEW

**Comment by ljleb** [comment]
I am not sure about this. What if I want to put these models on a ssd or a different drive instead? They can take up a lot of space together.

**Comment by lllyasviel** [comment]
but how we can help people like https://github.com/Mikubill/sd-webui-controlnet/issues/878
in some country the internet is not very good and model corruption is common
they will be disappointed when they cannot solve problems by removing controlnet and install it again

**Comment by ljleb** [comment]
Yes I agree. I think it's okay to change the defaults.

With the current changes here, everyone will have to download the preprocessor models twice. I was thinking there should be a less radical way to do this transition.

**Comment by lllyasviel** [comment]
"deleting sd-webui-controlnet folder and install again can solve all problems" should be the bottom line.
costumization and backwards compatibility are important, but not deadly
this is deadly

**Comment by lllyasviel** [comment]
a  “less radical way” does not exist because their files maybe already corrpted
detecting each file is not practical and not beneficial for future extending from community because it make things more complicated

**Comment by sanshaoyeyang** [comment]
We are stuck with this problem, please help

**Comment by sanshaoyeyang** [comment]
Traceback (most recent call last):
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 390, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 205, in openpose_face
    result = model_openpose(img, include_hand=False, include_face=True)
  File "J:\AI\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 79, in __call__
    self.face_estimation.model.to(self.device)
AttributeError: 'NoneType' object has no attribute 'model'

**Comment by ljleb** [comment]
Can't we just add a checkbox in the settings to change the annotator path? check it by default for new installs, and do not check it for existing installs.

**Comment by lllyasviel** [comment]
wait a minute, where clip_vision is downloaded?

**Comment by lllyasviel** [comment]
clip vision added. testing now

**Comment by lllyasviel** [comment]
yes we need a config but the starting point should be a case that "deleting sd-webui-controlnet folder and install again can solve all problems" 
we must achieve this in the first place, and this is emergency.
after this we can start thinking about other improvements

**Comment by ljleb** [comment]
I think this needs a bit more tinkering, it seems that the old model path is loaded by default if it exists:

```
https://github.com/Mikubill/sd-webui-controlnet/blob/0696c67cfef2bb991157470475583c3c7c8b45ae/annotator/leres/__init__.py#L42
```

**Pull request merged**
