### PR TITLE
Update depth_anythingV2

### PR DESCRIPTION
**Pull request by sdbds**
replace model to new V2 path
https://huggingface.co/depth-anything/Depth-Anything-V2-Large

### CODE REVIEW

**Comment by sdbds** [comment]
image

I tested it but the jaggies are noticeable, it's best to update the code in the python package just to be on the safe side
 (although the code doesn't seem to have changed much when I checked it)

**Comment by sdbds** [comment]
image
OK，they change dino model,too

**Review by huchenlei — COMMENTED** [review]
I think we should add a new preprocessor for that v2 model, so that people get consistent result with same infotext.

**Comment by huchenlei** [comment]
> image OK，they change dino model,too

I don't think that dino model change is the cause. The [commit](https://github.com/huchenlei/Depth-Anything/commit/e911178017ef4a3039c3599ca20327961388f932) happens on Jan 15th before I fork the repo on Jan 22nd.

**Comment by kagevazquez** [comment]
The output from this is really pixilated when used as a drop in replacement. I think they changed something in dinov2 for v2

**Comment by MackinationsAi** [comment]
I have update the sd-webui-controlnet repo to support depth_anything_v2 in this forked branch if you approve the pull request I'm about to submit. Forked Repo - https://github.com/MackinationsAi/sd-webui-controlnet

**Comment by sdbds** [comment]
> I have update the sd-webui-controlnet repo to support depth_anything_v2 in this forked branch if you approve the pull request I'm about to submit. Forked Repo - https://github.com/MackinationsAi/sd-webui-controlnet

Thanks for your contribution, I will review as well as test it as soon as possible.

**Comment by MackinationsAi** [comment]
> > I have update the sd-webui-controlnet repo to support depth_anything_v2 in this forked branch if you approve the pull request I'm about to submit. Forked Repo - https://github.com/MackinationsAi/sd-webui-controlnet
> 
> Thanks for your contribution, I will review as well as test it as soon as possible.

I still need to upload the new hf depth_anything_v2 transformers (which I will be doing next). I have tested it locally on my machine & it works really well!

**Pull request closed without merging**
