### PR TITLE
Update external_code.py   fix for issue 2132 2111

### PR DESCRIPTION
**Pull request by joergwa**
fix for https://github.com/Mikubill/sd-webui-controlnet/issues/2132 https://github.com/Mikubill/sd-webui-controlnet/issues/2111

### CODE REVIEW

**Comment by huchenlei** [comment]
Can you explain why this PR fixes the issue listed?

**Comment by joergwa** [comment]
> change line 340 in sd-webui-controlnet/internal_controlnet/external_code.py
> 
> from: script_args = list(p.script_args)
> to: script_args = p.script_args_value



p.script_args returns None, which it not iterable to create a list (raises the error).
p.script_args_value returns a list with None objects, which seems to be fine so far

```
print (type(p.script_args))
print (p.script_args)
print (type(p.script_args_value))
print (p.script_args_value)

<class 'NoneType'>
None
<class 'list'>
[None, None, None, None]
```


I am wondering, according to https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/processing.py#L256 p.script_args is the getter of p.script_args_value and I expect both return the same value but they don't.

My guess is, that somewhere p.script_args has been overwritten.

**Comment by Florisdk** [comment]
It works!! Thank you a lot! I signed up specifically to tell you:-)

**Comment by huchenlei** [comment]
Tested locally and most functionalities work fine. LGTM on merge.

**Pull request merged**
