### PR TITLE
Completely remove deprecated guess mode

### PR DESCRIPTION
**Pull request by lllyasviel**

### CODE REVIEW

**Comment by ljleb** [comment]
It is possible this breaks some extensions or external code. Are you sure this is a good idea? I think it is a better idea to let everybody know before making this breaking change.

**Comment by lllyasviel** [comment]
we already have **kwargs so it wont break things

**Comment by ljleb** [comment]
See for example: https://github.com/mix1009/sdwebuiapi/blob/650a2c93269e7e2931bee6e3f8134d7d8e536f89/webuiapi/webuiapi.py#L692

**Comment by ljleb** [comment]
We should tell people in one way or another, either though a discussion or a warning in console.

**Comment by lllyasviel** [comment]
good. added print

**Pull request merged**
