### PR TITLE
smart preview management, remove preview as inputs

### PR DESCRIPTION
**Pull request by lllyasviel**
smart preview management, remove preview as inputs
I tested openpose editor.
Please test yourself to see if anything is missing

### CODE REVIEW

**Comment by Ineman** [comment]
1. upload original image to controlnet
2. run postprocess to make canny preview
3. close original image
4. postprocess preview image only in controlnet
5. image generate -> doesn't work as controlnet

**Comment by lllyasviel** [comment]
> 1. upload original image to controlnet
> 2. run postprocess to make canny preview
> 3. close original image
> 4. postprocess preview image only in controlnet
> 5. image generate -> doesn't work as controlnet

nice catch. but this seems impossible to fix since gradio does not have callback when image is removed

**Comment by lllyasviel** [comment]
oh wait. it is possible in newer gradio

**Comment by lllyasviel** [comment]
unfortunately this cannot be solved as gradio has a bug that Image.clear is broken on the listener

**Comment by Ineman** [comment]
It worked by 'preview as input' in past.
If this feature doesn't necessarily have to be removed, I think it's more convenient to have it....

**Comment by lllyasviel** [comment]
image size only influence browser speed when uploading images.

**Comment by huchenlei** [comment]
LGTM. Thanks for fixing it. Verified that openpose editor still functions as expected.

**Comment by Prince-Mars** [comment]
Return preview as inputs! Please!

**Comment by silveroxides** [comment]
What bug prompted this change? Was there something not working previously?
Because there obviously are issues as a result of this commit.

**Comment by Prince-Mars** [comment]
I think the original picture has an impact on the result. In Canny mode for sure.
**Return preview as inputs! Please!**

**Comment by Prince-Mars** [comment]
> * upload original image to controlnet
> * run postprocess to make canny preview
> * close original image
> * postprocess preview image only in controlnet
> * image generate -> doesn't work as controlnet

Same error

**Pull request merged**
