### PR TITLE
add settings for annotator models path (follow-up)

### PR DESCRIPTION
**Pull request by ljleb**
Follow up of #891 

Because of https://github.com/Mikubill/sd-webui-controlnet/pull/881#issuecomment-1512665611, I am also changing the default path back to `<webui>/models`.

Related discussion: #45, #127

Controlnet is not the only extension using the models, IIUC it is a bad idea to locate them inside the extension directory.

### CODE REVIEW

**Comment by ljleb** [comment]
This removes the fallback intended to be implemented in #881. However this makes it so that everyone has to download the models again. This is not good for people that do not have a lot of internet bandwidth. For this reason, I am also changing the default path back to `<webui>/models`.

**Comment by ljleb** [comment]
Related discussion: #45, #127

**Comment by ljleb** [comment]
Ah actually, the fallback is to a directory inside of the extension so it is not a problem. I reverted the removal of the fallback.

**Comment by ljleb** [comment]
@lllyasviel IIUC you are against some of these changes, let me know if you are interested in discussing it.

**Comment by lllyasviel** [comment]
in fact adding config is also not very robust since if people remove controlnet folder, the configs cannot be removed.
if their configs are wrong, they  will failed to use controlnet forever.
we should make sure that people can undo everything by only changing things they know very well and minimize the risk if people forget things.

**Comment by ljleb** [comment]
The config does not prevent users from starting the webui, and they can always change it by simply saving the settings and reloading the ui.

Let's see. Here are the possible constraints and requirements for this:
- fixing corrupted models should be as simple as possible. even fail-safe if possible
- models should be able to be reused between different extensions
- some users already have annotator models located at these paths now:
   - /extensions/sd-webui-controlnet/annotator
   - /extensions/sd-webui-controlnet/annotator/downloads
   - /models
- some of these models are corrupted, and some are not. Only corrupted models under /models pose a meaningful problem.

This sums up the situation. We could add a facility in the webui to manage these models maybe? Perhaps in our own tab, or in the settings if that is possible.

**Comment by ljleb** [comment]
If we want an easy factory reset, AND we have to place annotator models under /models, then there is no way around having to add a script to be ran from command line, or a tab in the webui.

Another option is to create a new extension to manage all models of the webui.

**Comment by ljleb** [comment]
As of right now I am busy, but I will look into this in 1 day or 2.

**Comment by missionfloyd** [comment]
If corruption's a concern, why not verify checksums when they're loaded and redownload if necessary?

**Comment by ljleb** [comment]
Maybe that could work. Is it possible that the model perpetually fails to download though?

Maybe verify the checksum, but crash with a descriptive error message instructing how to manually download?

**Comment by lllyasviel** [comment]
I still do not agree with this. Perhaps wait one or two months when everyone has a stable version and then we can safely do this.
Recently people are updating.
Not having this has significant benefits.

**Comment by devingfx** [comment]
Hi guys!
I have trouble using the commandline arguments to move the models and annotators folder to a place outside extensions folder (and outside webui also)...
Is this supposed to be in production ? Or maybe active on a certain commit ?

Here is my commandline args for CN:
```
--controlnet-dir /home/dig/dev/AI/models/img/ControlNet/models --controlnet-annotator-models-path /home/dig/dev/AI/models/img/ControlNet/annotators
```
Here is my full webui commandline string (if maybe any conflict with a full CPU config):
```
Launching Web UI with arguments: --ckpt-dir /home/dig/dev/AI/models/img/stable-diffusion --lora-dir /home/dig/dev/AI/models/img/lora --embeddings-dir /home/dig/dev/AI/models/img/embeddings --textual-inversion-templates-dir /home/dig/dev/AI/models/img/textual_inversion_templates --hypernetwork-dir /home/dig/dev/AI/models/img/hypernetworks --enable-insecure-extension-access --api --skip-torch-cuda-test --opt-channelslast --use-cpu all --no-half --precision autocast --controlnet-dir /home/dig/dev/AI/models/img/ControlNet/models --controlnet-annotator-models-path /home/dig/dev/AI/models/img/ControlNet/annotators
```
...and here is the error I get:
```bash
Error loading script: controlnet.py
Traceback (most recent call last):
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 84, in <module>
    global_state.update_cn_models()
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 208, in update_cn_models
    found = get_all_models(sort_by, filter_by, path)
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 175, in get_all_models
    fileinfos = traverse_all_files(path, [])
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 163, in traverse_all_files
    for entry in os.scandir(curr_path)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/models'
```

Could somebody help me point out why CN is still searching the models in old location ?

THX

**Comment by huchenlei** [comment]
> Hi guys! I have trouble using the commandline arguments to move the models and annotators folder to a place outside extensions folder (and outside webui also)... Is this supposed to be in production ? Or maybe active on a certain commit ?
> 
> Here is my commandline args for CN:
> 
> ```
> --controlnet-dir /home/dig/dev/AI/models/img/ControlNet/models --controlnet-annotator-models-path /home/dig/dev/AI/models/img/ControlNet/annotators
> ```
> 
> Here is my full webui commandline string (if maybe any conflict with a full CPU config):
> 
> ```
> Launching Web UI with arguments: --ckpt-dir /home/dig/dev/AI/models/img/stable-diffusion --lora-dir /home/dig/dev/AI/models/img/lora --embeddings-dir /home/dig/dev/AI/models/img/embeddings --textual-inversion-templates-dir /home/dig/dev/AI/models/img/textual_inversion_templates --hypernetwork-dir /home/dig/dev/AI/models/img/hypernetworks --enable-insecure-extension-access --api --skip-torch-cuda-test --opt-channelslast --use-cpu all --no-half --precision autocast --controlnet-dir /home/dig/dev/AI/models/img/ControlNet/models --controlnet-annotator-models-path /home/dig/dev/AI/models/img/ControlNet/annotators
> ```
> 
> ...and here is the error I get:
> 
> ```shell
> Error loading script: controlnet.py
> Traceback (most recent call last):
>   File "/home/dig/dev/AI/A1111/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
>     script_module = script_loading.load_module(scriptfile.path)
>   File "/home/dig/dev/AI/A1111/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 84, in <module>
>     global_state.update_cn_models()
>   File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 208, in update_cn_models
>     found = get_all_models(sort_by, filter_by, path)
>   File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 175, in get_all_models
>     fileinfos = traverse_all_files(path, [])
>   File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 163, in traverse_all_files
>     for entry in os.scandir(curr_path)]
> FileNotFoundError: [Errno 2] No such file or directory: '/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/models'
> ```
> 
> Could somebody help me point out why CN is still searching the models in old location ?
> 
> THX

Can you file a new issue, so that it becomes more trackable?

**Pull request closed without merging**
