### PR TITLE
Support for new T2I adapters (color, style)

### PR DESCRIPTION
**Pull request by catboxanon**
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/476

[Color adapter](https://github.com/TencentARC/T2I-Adapter/blob/main/docs/examples.md#color-adapter-spatial-palette) should be working. [Style adapter](https://github.com/TencentARC/T2I-Adapter/blob/main/docs/examples.md#style-adapter) is unable to load currently due to a tensor dimension mismatch (not the most familiar with this, sorry). Opening as a draft for now. Feel free to take this code and open a new PR if you wish, as I'm doubtful I can resolve this on my own.

Examples below are at default settings, no tweaking or cherrypicking.

| Image | Disabled | Enabled |
|:-------------------------:|:-------------------------:|:-------------------------:|
|  |   |  |
|  |   |  |
|  |   |  |

### CODE REVIEW

**Comment by Mikubill** [comment]
Quick test!

| Image | Annotator | Output |
|:-------------------------:|:-------------------------:|:-------------------------:|
|  |   |  |
|  |  (clip) |  |

Seems the preprocessing (>768) is required for larger resolution.

**Comment by AugmentedRealityCat** [comment]
Checking this out right now !

**Comment by AugmentedRealityCat** [comment]
Just wanted to let you know that both `color` and `style` are working, as well as their pre-processor. Style is giving me a hard time - it's quite difficult to understand how it affects the image. It will take practice ! 
But on a technical level everything seems to work very well, without any apparent bugs. 
Thanks a lot to you all for making this happen !

**Comment by Mikubill** [comment]
Looks good.
We still need to add some intro about the new model - do you have time to edit the readme? or I will commit later

**Comment by mikearts** [comment]
Error when trying to generate color adapter. t2iadapter_color-fp16.safetensors and t2iadapter_color_sd14v1.yaml in one folder.
`Loading model: t2iadapter_color-fp16 [743b5c62]
Loaded state_dict from [F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\t2iadapter_color-fp16.safetensors]
Error running process: F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 742, in process
    model_net = self.load_control_model(p, unet, model, lowvram)
  File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 541, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 579, in build_control_model
    network = network_module(
  File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 81, in __init__
    self.control_model.load_state_dict(state_dict)
  File "F:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Adapter:
        Missing key(s) in state_dict: "body.0.block1.weight", "body.0.block1.bias", "body.0.block2.weight", "body.0.block2.bias", "body.1.block1.weight", "body.1.block1.bias", "body.1.block2.weight", "body.1.block2.bias", "body.2.block1.weight", "body.2.block1.bias", "body.2.block2.weight", "body.2.block2.bias", "body.3.block1.weight", "body.3.block1.bias", "body.3.block2.weight", "body.3.block2.bias", "body.4.in_conv.weight", "body.4.in_conv.bias", "body.4.block1.weight", "body.4.block1.bias", "body.4.block2.weight", "body.4.block2.bias", "body.5.block1.weight", "body.5.block1.bias", "body.5.block2.weight", "body.5.block2.bias", "body.6.block1.weight", "body.6.block1.bias", "body.6.block2.weight", "body.6.block2.bias", "body.7.block1.weight", "body.7.block1.bias", "body.7.block2.weight", "body.7.block2.bias", "conv_in.weight", "conv_in.bias".
        Unexpected key(s) in state_dict: "body.0.body.0.block1.bias", "body.0.body.0.block1.weight", "body.0.body.0.block2.bias", "body.0.body.0.block2.weight", "body.0.body.1.block1.bias", "body.0.body.1.block1.weight", "body.0.body.1.block2.bias", "body.0.body.1.block2.weight", "body.0.body.2.block1.bias", "body.0.body.2.block1.weight", "body.0.body.2.block2.bias", "body.0.body.2.block2.weight", "body.0.body.3.block1.bias", "body.0.body.3.block1.weight", "body.0.body.3.block2.bias", "body.0.body.3.block2.weight", "body.0.in_conv.bias", "body.0.in_conv.weight", "body.0.out_conv.bias", "body.0.out_conv.weight", "body.1.body.0.block1.bias", "body.1.body.0.block1.weight", "body.1.body.0.block2.bias", "body.1.body.0.block2.weight", "body.1.body.1.block1.bias", "body.1.body.1.block1.weight", "body.1.body.1.block2.bias", "body.1.body.1.block2.weight", "body.1.body.2.block1.bias", "body.1.body.2.block1.weight", "body.1.body.2.block2.bias", "body.1.body.2.block2.weight", "body.1.body.3.block1.bias", "body.1.body.3.block1.weight", "body.1.body.3.block2.bias", "body.1.body.3.block2.weight", "body.1.in_conv.bias", "body.1.in_conv.weight", "body.1.out_conv.bias", "body.1.out_conv.weight", "body.2.body.0.block1.bias", "body.2.body.0.block1.weight", "body.2.body.0.block2.bias", "body.2.body.0.block2.weight", "body.2.body.1.block1.bias", "body.2.body.1.block1.weight", "body.2.body.1.block2.bias", "body.2.body.1.block2.weight", "body.2.body.2.block1.bias", "body.2.body.2.block1.weight", "body.2.body.2.block2.bias", "body.2.body.2.block2.weight", "body.2.body.3.block1.bias", "body.2.body.3.block1.weight", "body.2.body.3.block2.bias", "body.2.body.3.block2.weight", "body.2.out_conv.bias", "body.2.out_conv.weight", "body.3.body.0.block1.bias", "body.3.body.0.block1.weight", "body.3.body.0.block2.bias", "body.3.body.0.block2.weight", "body.3.body.1.block1.bias", "body.3.body.1.block1.weight", "body.3.body.1.block2.bias", "body.3.body.1.block2.weight", "body.3.body.2.block1.bias", "body.3.body.2.block1.weight", "body.3.body.2.block2.bias", "body.3.body.2.block2.weight", "body.3.body.3.block1.bias", "body.3.body.3.block1.weight", "body.3.body.3.block2.bias", "body.3.body.3.block2.weight", "body.3.in_conv.bias", "body.3.in_conv.weight", "body.3.out_conv.bias", "body.3.out_conv.weight".
        size mismatch for body.2.in_conv.weight: copying a param with shape torch.Size([320, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 320, 1, 1]).
        size mismatch for body.2.in_conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).`

**Comment by MhmdSheref** [comment]
> Error when trying to generate color adapter. t2iadapter_color-fp16.safetensors and t2iadapter_color_sd14v1.yaml in one folder. `Loading model: t2iadapter_color-fp16 [743b5c62] Loaded state_dict from [F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\t2iadapter_color-fp16.safetensors] Error running process: F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py Traceback (most recent call last): File "F:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 386, in process script.process(p, *script_args) File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 742, in process model_net = self.load_control_model(p, unet, model, lowvram) File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 541, in load_control_model model_net = self.build_control_model(p, unet, model, lowvram) File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 579, in build_control_model network = network_module( File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 81, in __init__ self.control_model.load_state_dict(state_dict) File "F:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for Adapter: Missing key(s) in state_dict: "body.0.block1.weight", "body.0.block1.bias", "body.0.block2.weight", "body.0.block2.bias", "body.1.block1.weight", "body.1.block1.bias", "body.1.block2.weight", "body.1.block2.bias", "body.2.block1.weight", "body.2.block1.bias", "body.2.block2.weight", "body.2.block2.bias", "body.3.block1.weight", "body.3.block1.bias", "body.3.block2.weight", "body.3.block2.bias", "body.4.in_conv.weight", "body.4.in_conv.bias", "body.4.block1.weight", "body.4.block1.bias", "body.4.block2.weight", "body.4.block2.bias", "body.5.block1.weight", "body.5.block1.bias", "body.5.block2.weight", "body.5.block2.bias", "body.6.block1.weight", "body.6.block1.bias", "body.6.block2.weight", "body.6.block2.bias", "body.7.block1.weight", "body.7.block1.bias", "body.7.block2.weight", "body.7.block2.bias", "conv_in.weight", "conv_in.bias". Unexpected key(s) in state_dict: "body.0.body.0.block1.bias", "body.0.body.0.block1.weight", "body.0.body.0.block2.bias", "body.0.body.0.block2.weight", "body.0.body.1.block1.bias", "body.0.body.1.block1.weight", "body.0.body.1.block2.bias", "body.0.body.1.block2.weight", "body.0.body.2.block1.bias", "body.0.body.2.block1.weight", "body.0.body.2.block2.bias", "body.0.body.2.block2.weight", "body.0.body.3.block1.bias", "body.0.body.3.block1.weight", "body.0.body.3.block2.bias", "body.0.body.3.block2.weight", "body.0.in_conv.bias", "body.0.in_conv.weight", "body.0.out_conv.bias", "body.0.out_conv.weight", "body.1.body.0.block1.bias", "body.1.body.0.block1.weight", "body.1.body.0.block2.bias", "body.1.body.0.block2.weight", "body.1.body.1.block1.bias", "body.1.body.1.block1.weight", "body.1.body.1.block2.bias", "body.1.body.1.block2.weight", "body.1.body.2.block1.bias", "body.1.body.2.block1.weight", "body.1.body.2.block2.bias", "body.1.body.2.block2.weight", "body.1.body.3.block1.bias", "body.1.body.3.block1.weight", "body.1.body.3.block2.bias", "body.1.body.3.block2.weight", "body.1.in_conv.bias", "body.1.in_conv.weight", "body.1.out_conv.bias", "body.1.out_conv.weight", "body.2.body.0.block1.bias", "body.2.body.0.block1.weight", "body.2.body.0.block2.bias", "body.2.body.0.block2.weight", "body.2.body.1.block1.bias", "body.2.body.1.block1.weight", "body.2.body.1.block2.bias", "body.2.body.1.block2.weight", "body.2.body.2.block1.bias", "body.2.body.2.block1.weight", "body.2.body.2.block2.bias", "body.2.body.2.block2.weight", "body.2.body.3.block1.bias", "body.2.body.3.block1.weight", "body.2.body.3.block2.bias", "body.2.body.3.block2.weight", "body.2.out_conv.bias", "body.2.out_conv.weight", "body.3.body.0.block1.bias", "body.3.body.0.block1.weight", "body.3.body.0.block2.bias", "body.3.body.0.block2.weight", "body.3.body.1.block1.bias", "body.3.body.1.block1.weight", "body.3.body.1.block2.bias", "body.3.body.1.block2.weight", "body.3.body.2.block1.bias", "body.3.body.2.block1.weight", "body.3.body.2.block2.bias", "body.3.body.2.block2.weight", "body.3.body.3.block1.bias", "body.3.body.3.block1.weight", "body.3.body.3.block2.bias", "body.3.body.3.block2.weight", "body.3.in_conv.bias", "body.3.in_conv.weight", "body.3.out_conv.bias", "body.3.out_conv.weight". size mismatch for body.2.in_conv.weight: copying a param with shape torch.Size([320, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 320, 1, 1]). size mismatch for body.2.in_conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).`

I'm having the same problem here

**Comment by MhmdSheref** [comment]
actually, my bad, 
> I guess that you need to put the file "t2iadapter_color_sd14v1.yaml" in the same folder as the file "/models/ControlNet/t2iadapter_color_sd14v1.pth".

I just had to rename the yaml files to be the same name as the models... depending on where you got the models from they might have a diffrent name

**Comment by Stan-Stani** [comment]
Where do you get the yml files? I can't find them.

**Comment by albamuth** [comment]
I would also like to know where t2iadapter_color_sd14v1.yaml is located?

**Comment by z0z0Official** [comment]
> In this repo. [https://github.com/Mikubill/sd-webui-controlnet/blob/main/models/t2iadapter_color_sd14v1.yaml ](https://github.com/Mikubill/sd-webui-controlnet/blob/main/models/t2iadapter_color_sd14v1.yaml)

Link doesn't work!

**Pull request merged**
