### PR TITLE
Add inpaint upload mode for txt2img use

### PR DESCRIPTION
**Pull request by OedoSoldier**

### CODE REVIEW

**Comment by lllyasviel** [comment]
can you share a screenshot about how it looks like?
and if the design looks good we will also consider adding gradio image crop in a similar way - like https://github.com/Mikubill/sd-webui-controlnet/issues/1205 https://github.com/Mikubill/sd-webui-controlnet/pull/483

**Comment by lllyasviel** [comment]
unfortunately, mask blur does not make sence in CN inpaint  - controlnet inpaint must receive binarized mask
https://github.com/Mikubill/sd-webui-controlnet/blob/539d2fc990bc592dd7e482ecabffdc511073dbed/scripts/controlnet.py#L890

This can be merged after the mask blur slider is removed

**Comment by OedoSoldier** [comment]
Oh, I overlooked that.

As for crop function, I think using `gr.State()` to store the original image can helps, maybe I'll try it later

**Comment by lllyasviel** [comment]
after taking a look at this, crop is not quite related.

**Comment by lllyasviel** [comment]
unfortunately we cannot modify ControlNetUnit for this - this change is too big and will affect all apis and other extensions.

**Comment by lllyasviel** [comment]
can we remove all codes related to ControlNetUnit? they seems not related to the functionality and it can work without it

**Comment by lllyasviel** [comment]
it seems that we need more considerations on this - although we want to avoid ControlNetUnit, if we do not do it using unit, then all units will share one input - if you use this mask upload in multiple units, bugs are likely to appear.
it seems that we do not have very good solution to this, and will consider this in next big update or try to find some solution

**Pull request closed without merging**
