### PR TITLE
Add Automatic Prompt

### PR DESCRIPTION
**Pull request by cjfghk5697**
[Add Automatic Prompt #237](https://github.com/Mikubill/sd-webui-controlnet/issues/237)

I have been writing code about **Automatic Prompt**. However, it is not yet perfect now. Probably, this code is got problems. I will test this code this weekend.

### CODE REVIEW

**Comment by cjfghk5697** [comment]
- [ ] Add Option
```python
if p.prompt is "" and p.automatic:
   p.prompt=automatic_prompt(input_image,h,w)
```
If user want to use the Automatic Prompt, p.automatic option must be True.
- [ ] Add description

**Comment by Mikubill** [comment]
Looks good! Maybe we should add some offload for lowvram users

**Comment by cjfghk5697** [comment]
@Mikubill  
I agree that! Added to the checkbox.

**Comment by cjfghk5697** [comment]
The BLIP model is cloning from the [github](https://github.com/salesforce/BLIP). You know that, this model is heavy. Therefore, you said, it is need to offload. 

I'm not sure, only when automatic is True, git clone and download the model.
```python
import git
git.Git("/").clone("https://github.com/salesforce/BLIP.git")
from BLIP.models.blip import blip_decoder

model_url = 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth'
```

**Comment by Mikubill** [comment]
Hmm..maybe we could add some hints to tell user install BILP manually

**Comment by cjfghk5697** [comment]
Oh... That's right and better solution😅I'll turn it into code before I fix it

**Comment by cjfghk5697** [comment]
image
@Mikubill 
Hi! I tested it by adding code to add a ui once, but the checkbox is not added. How add the checkbox?  
```python
automatic = gr.Checkbox(label="Automatic Mode", value=False)
```

I'm really sorry to bother you

**Pull request closed without merging**
