### PR TITLE
forward web api to external_code api

### PR DESCRIPTION
**Pull request by ljleb**
Centralizes the preprocessors and unloadables to one place.

@lllyasviel you may be interested in reviewing this.

Related: #809

### CODE REVIEW

**Comment by kft334** [comment]
Line 219 should probably be changed to:
results.append(processor_module(img=img, res=controlnet_processor_res, thr_a=controlnet_threshold_a, thr_b=controlnet_threshold_b)[0])

I'm getting empty success responses without the index.

**Comment by lllyasviel** [comment]
it seems conflict the new added mediapipe face. can we fix?

**Comment by ljleb** [comment]
merged main into this. I am curious whether the preprocessor names will be appropriate? I am not sure why we had this huge list of `if`-`elif`s. In any case I think we do not want to have to use different model names through the web api vs the gradio interface or the external code api.

**Comment by ljleb** [comment]
Alias names are not taken into consideration right now, working on a fix

**Pull request merged**
