### PR TITLE
Reland "Add Densepose (TorchScript)"

### PR DESCRIPTION
**Pull request by huchenlei**
Reverts Mikubill/sd-webui-controlnet#2457

### CODE REVIEW

**Comment by RGX650** [comment]
@huchenlei if this can help you:
https://github.com/VTON-Project/Body_Segmentation_DensePose
https://github.com/dajes/DensePose-TorchScript

**Comment by theclashoftitans** [comment]
This preprocessor is placed under OpenPose, but I don't see a corresponding model. Is the model file missing for this preprocessor?


When I set the Preprocessor to "densepose (pruple bg & purple torso)"  or "densepose_parula (black bg & blue torso)" and leave Model empty, nothing happens (obviously), and the preprocessor doesn't make an attempt to download a model file.

**Comment by huchenlei** [comment]
See original PR: https://github.com/Mikubill/sd-webui-controlnet/pull/2314. There are 2 models that you can download.

**Comment by theclashoftitans** [comment]
Thanks, but this is quite confusing as a user.

1. Shouldn't this either be documented properly, maybe in the README.md or wiki? Asking users to dig into merged PRs for each functionality is not user friendly.
2. Other preprocessors that require an external model checks if the file exists already, and if not, automatically downloads the required file. Shouldn't this do the same?
3. I downloaded and put those files under the controlnet's models directory. When I select the preprocessor, the model is not automatically selected, again a behavior that is different from other preprocessors.

**Comment by theclashoftitans** [comment]
I did some tests. The CivitAI model works with the parula preprocessor (I selected the model manually; I had to change the category from OpenPose to All to do that since it doesn't show up in OpenPose). However,  "viridis" model with "densepose (pruple bg & purple torso)" gives completely irrelevant results.

Are you sure the following link is the correct model corresponding to the ""densepose (pruple bg & purple torso)"" preprocessor? https://huggingface.co/zcxu-eric/MagicAnimate/blob/main/densepose_controlnet/diffusion_pytorch_model.safetensors

**Comment by huchenlei** [comment]
Well. I did not draft the PR nor did I do any testing on the model listed. You probably want to ask initial PR author @Fannovel16.

**Comment by sdbds** [comment]
> I did some tests. The CivitAI model works with the parula preprocessor (I selected the model manually; I had to change the category from OpenPose to All to do that since it doesn't show up in OpenPose). However, "viridis" model with "densepose (pruple bg & purple torso)" gives completely irrelevant results.
> 
> Are you sure the following link is the correct model corresponding to the ""densepose (pruple bg & purple torso)"" preprocessor? https://huggingface.co/zcxu-eric/MagicAnimate/blob/main/densepose_controlnet/diffusion_pytorch_model.safetensors

this is another video model to use，not controlnet model

**Pull request merged**
