### PR TITLE
:bug: Allow functionally equiv stale units

### PR DESCRIPTION
**Pull request by huchenlei**

### CODE REVIEW

**Comment by lllyasviel** [comment]
I dont think we should give stale warnings when the unit is hacked by 3rd extensions?

**Comment by huchenlei** [comment]
> I dont think we should give stale warnings when the unit is hacked by 3rd extensions?

Maybe demote that log to debug? I think it could be useful during debug, but not so useful for a common user.

**Comment by lllyasviel** [comment]
and it should be safer to just make sure all keys in the toy unit exist in the instance unit, and ignore extra keys, as 3rd extensions would add extra keys to the unit

**Comment by lllyasviel** [comment]
and probably ignore any key begin with "__" to avoid strange problems

**Comment by lllyasviel** [comment]
like some one hacked the class and write a "__doc__" in the class then it will take one year to find out where is wrong and why controlnet cannot read the unit

**Comment by huchenlei** [comment]
> 

`vars` do not return keys begin with "__", `dir` does that.

**Comment by lllyasviel** [comment]
oh that make sense

**Pull request merged**
